(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.phone2rubinecircleai = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// phone2-rubine-circle.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgHCsQgvgZgqgsQhBhGgShMQgShMAngqIAUgVQANgOATAAQATAAANAOIAlAoQANAOAAATQAAATgNAOIggAjQAVAkAcAdQAdAfAfAUIAgghQANgOATAAQATAAANAOIAlAnQANAOAAAUQAAATgNAOIgTAVQgbAcgtAAQgqAAgvgZgAh8ioIgTAVQgiAjATBGQASBEA7A/QAmApArAXQAsAYAmAAQAlAAAUgWIAUgVQAHgIAAgLQAAgMgHgIIgmgoQgGgHgLAAQgLAAgHAHIglAoQgGAGgGgEQglgXgjglQghgjgWgoQgEgHAFgFIAmgnQAHgIAAgMQAAgLgHgJIgmgnQgGgIgLAAQgLAAgHAIg");
	this.shape.setTransform(28.0908,26.125);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E40571").s().p("Ai/DAQhPhQAAhwQAAhvBPhQQBQhPBvAAQBwAABQBPQBPBQAABvQAABwhPBQQhQBPhwAAQhvAAhQhPg");
	this.shape_1.setTransform(27.125,27.125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,54.3,54.3);


(lib.HEAD4 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhjBxQggguAAhDQAAhDAggtQAkg0A/AAQBAAAAkA0QAgAtAABDQAABDggAuQgkA0hAAAQg/AAgkg0gAg+AAQAABoA+AAQA/AAAAhoQAAhog/AAQg+AAAABog");
	this.shape.setTransform(-78.975,17.475);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgRDQIAAgsQhGgGgsgrIAmg1QAfAhAtAHIAAhJQgvgMgXgQQghgYAAgrQAAglAbgbQAdgbAvgFIAAgsIAsAAIAAAtQA6AHAnAkIgmAyQgYgWgjgJIAABCQAwAMAXAQQAiAYAAAsQAAApgaAbQgcAcgzAFIAAAsgAAbBnQAkgGAAgbQAAgTgkgMgAgyhHQAAARAhAKIAAg6QghAEAAAbg");
	this.shape_1.setTransform(-108.575,17.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_1
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgkAeIAKgPQAFAEAIAEQAIADAGABQAOgBAAgIQAAgFgHgCIgQgDQgYgHAAgRQgBgLAJgHQAKgJAOAAQAUAAANAMIgIAQQgKgKgPAAQgEAAgEACQgDADAAADQAAAEAHACIAQAEQAYAGAAASQAAAMgJAHQgJAIgSAAQgVAAgPgOg");
	this.shape_2.setTransform(119.5,27.75);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgdAgQgMgMAAgUQAAgRAMgNQAMgNASAAQASAAAMANQALANAAATIAAAFIg8AAQABAIAGAFQAGAGAJAAQAOAAAIgIIAKAOQgMAMgWAAQgSAAgNgMgAAVgHQAAgHgFgEQgGgHgJAAQgJAAgFAHQgFAEgBAHIAoAAIAAAAg");
	this.shape_3.setTransform(110.825,27.75);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgKA5IAAhxIAVAAIAABxg");
	this.shape_4.setTransform(103.875,26.175);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgUAuIAAAKIgVAAIAAhxIAVAAIAAAqQAKgNAPAAQAQAAALAMQAKAMAAATQAAAUgLAMQgKALgQAAQgOAAgLgMgAgLgFQgFACgEADIAAAeQAEAEAFACQAFADAFAAQAIAAAHgHQAFgGAAgLQAAgLgFgGQgHgGgIAAQgFAAgFADg");
	this.shape_5.setTransform(97,26.275);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgKA7IAAhSIAVAAIAABSgAgIgkQgEgEAAgFQAAgFAEgEQAEgEAEAAQAFAAAFAEQADAEAAAFQAAAFgDAEQgFAEgFAAQgEAAgEgEg");
	this.shape_6.setTransform(89.55,26.025);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgNAfIAAgqIgOAAIAAgTIAOAAIAAgXIAVAAIAAAXIARAAIAAATIgRAAIAAAkQAAAJAHAAQAGAAACgCIAEAQQgFAGgNAAQgWAAAAgXg");
	this.shape_7.setTransform(84.5,26.725);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgZAfQgMgMAAgTQAAgSAMgMQANgMASgBQAVABALAPIgOANQgGgJgLAAQgJAAgHAHQgGAHAAAJQAAALAGAHQAHAGAJAAQALAAAGgJIAOAOQgLAPgVAAQgSAAgNgNg");
	this.shape_8.setTransform(77.475,27.75);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgmAQIAAg5IAWAAIAAAxQAAAPAPAAQAKAAAIgJIAAg3IAWAAIAABRIgWAAIAAgKQgMAMgQAAQgbAAAAgag");
	this.shape_9.setTransform(68.125,27.875);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgfAvQgKgMAAgUQAAgTAKgMQALgMAPAAQAPAAAKANIAAgqIAWAAIAABxIgWAAIAAgKQgKAMgPAAQgPAAgLgLgAgNgCQgFAGAAALQAAALAFAGQAGAHAIAAQAGAAAFgDQAFgCADgEIAAgeQgDgDgFgDQgFgCgGAAQgIAAgGAGg");
	this.shape_10.setTransform(57.9,26.275);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgdAgQgMgMAAgUQAAgRAMgNQAMgNASAAQASAAAMANQALANAAATIAAAFIg8AAQABAIAGAFQAGAGAJAAQAOAAAIgIIAKAOQgMAMgWAAQgSAAgNgMgAAVgHQAAgHgFgEQgGgHgJAAQgJAAgFAHQgFAEgBAHIAoAAIAAAAg");
	this.shape_11.setTransform(48.475,27.75);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgeAvQgLgMAAgUQAAgTALgMQAJgMARAAQAOAAAKANIAAgqIAWAAIAABxIgWAAIAAgKQgKAMgOAAQgRAAgJgLgAgMgCQgHAGABALQgBALAHAGQAFAHAIAAQAGAAAFgDQAFgCADgEIAAgeQgDgDgFgDQgFgCgGAAQgIAAgFAGg");
	this.shape_12.setTransform(38.4,26.275);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgfAvQgKgMAAgUQAAgTAKgMQALgMAPAAQAQAAAJANIAAgqIAWAAIAABxIgWAAIAAgKQgKAMgPAAQgPAAgLgLgAgNgCQgFAGAAALQAAALAFAGQAGAHAJAAQAFAAAFgDQAFgCADgEIAAgeQgDgDgFgDQgFgCgFAAQgJAAgGAGg");
	this.shape_13.setTransform(24.05,26.275);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AARAqIAAgwQAAgQgPAAQgLAAgHAJIAAA3IgWAAIAAhRIAWAAIAAAKQALgNARAAQAbAAAAAbIAAA5g");
	this.shape_14.setTransform(14.325,27.65);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgcAlQgKgIAAgNQAAgNAKgHQAIgFALAAQARAAAIAJIAAgKQAAgGgEgEQgGgEgHAAQgNAAgKAKIgJgQQAPgNAUAAQAQAAAKAIQAKAHABARIAAA0IgXAAIAAgIQgIALgRAAQgKAAgJgHgAgLAIQgFACABAHQgBAFAFAEQAEADAHAAQALAAAFgIIAAgKQgFgHgLAAQgHAAgEAEg");
	this.shape_15.setTransform(4.5,27.75);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgjAeIAJgPQAFAEAIAEQAIADAHABQANgBAAgIQABgFgIgCIgQgDQgZgHABgRQAAgLAIgHQAJgJAQAAQASAAAOAMIgIAQQgKgKgOAAQgGAAgDACQgDADgBADQAAAEAIACIAQAEQAZAGAAASQAAAMgKAHQgKAIgQAAQgWAAgOgOg");
	this.shape_16.setTransform(-8.45,27.75);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgjA4IADgSIAHAAQAJABACgHIAEgGIgihTIAXAAIAVA5IAVg5IAYAAIgnBfQgEALgIAFQgGAEgNAAQgGAAgEgCg");
	this.shape_17.setTransform(-16.8,29.45);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgcAlQgKgIAAgNQAAgNAKgHQAIgFALAAQARAAAIAJIAAgKQAAgGgEgEQgGgEgHAAQgNAAgKAKIgJgQQAPgNAUAAQAQAAAKAIQAKAHABARIAAA0IgXAAIAAgIQgIALgRAAQgKAAgJgHgAgLAIQgFACABAHQgBAFAFAEQAEADAHAAQALAAAFgIIAAgKQgFgHgLAAQgHAAgEAEg");
	this.shape_18.setTransform(-26.1,27.75);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgpA6IAAhxIAWAAIAAAKQAJgMAPAAQARAAAJALQALAMAAAUQAAAUgLALQgJAMgRAAQgPAAgJgNIAAAqgAgLgjQgGADgCAEIAAAcQACAEAGADQAFACAFAAQAJAAAFgGQAHgGgBgLQABgKgHgHQgFgHgJAAQgFAAgFADg");
	this.shape_19.setTransform(-35.15,29.225);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgfAeQgMgLAAgTQAAgRAMgNQAMgNATAAQAUAAAMANQAMANAAARQAAATgMALQgMAOgUAAQgTAAgMgOgAgPgQQgFAHAAAJQAAALAFAGQAGAHAJAAQAKAAAGgHQAFgGAAgLQAAgJgFgHQgGgHgKAAQgJAAgGAHg");
	this.shape_20.setTransform(-45.375,27.75);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgZAfQgMgMAAgTQAAgSAMgMQANgMASgBQAVABALAPIgOANQgGgJgLAAQgJAAgHAHQgGAHAAAJQAAALAGAHQAHAGAJAAQALAAAGgJIAOAOQgLAPgVAAQgSAAgNgNg");
	this.shape_21.setTransform(-54.425,27.75);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgMARQAFgCADgFQAEgFABgEIgDAAQgEAAgEgCQgDgEgBgFQAAgGAFgEQAEgEAFAAQAFAAAFAFQAEAFAAAIQABASgSANg");
	this.shape_22.setTransform(114.05,14.675);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgjAeIAJgPQAFAEAIAEQAIADAHABQANgBAAgIQABgFgIgCIgQgDQgZgHABgRQAAgLAIgHQAJgJAQAAQASAAAOAMIgIAPQgKgJgOAAQgGAAgDACQgDADgBADQAAAEAIACIAQAEQAZAGAAASQAAAMgKAHQgKAIgQAAQgWAAgOgOg");
	this.shape_23.setTransform(107.65,10.65);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAoAqIAAgzQAAgNgMAAQgLAAgGAJIAAA3IgVAAIAAgzQAAgNgNAAQgKAAgHAJIAAA3IgVAAIAAhRIAVAAIAAAKQAEgEAGgDQAJgGAIAAQASABAEAPQAEgHAIgDQAIgGAJAAQAYAAAAAaIAAA6g");
	this.shape_24.setTransform(96.375,10.55);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgmAQIAAg5IAWAAIAAAxQAAAPAPAAQAKAAAIgJIAAg3IAWAAIAABRIgWAAIAAgKQgMAMgQAAQgbAAAAgag");
	this.shape_25.setTransform(84.125,10.775);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgKA7IAAhSIAVAAIAABSgAgIgkQgEgEAAgFQAAgFAEgEQAEgEAEAAQAFAAAFAEQADAEAAAFQAAAFgDAEQgFAEgFAAQgEAAgEgEg");
	this.shape_26.setTransform(76.95,8.925);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAoAqIAAgzQAAgNgMAAQgLAAgGAJIAAA3IgVAAIAAgzQAAgNgNAAQgKAAgHAJIAAA3IgVAAIAAhRIAVAAIAAAKQAEgEAGgDQAJgGAIAAQASABAEAPQAEgHAIgDQAIgGAJAAQAYAAAAAaIAAA6g");
	this.shape_27.setTransform(67.525,10.55);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgdAgQgMgMAAgUQAAgRAMgNQAMgNASAAQASAAAMANQALANAAATIAAAFIg8AAQABAIAGAFQAGAGAJAAQAOAAAIgIIAKAOQgMAMgWAAQgSAAgNgMgAAVgHQAAgHgFgEQgGgHgJAAQgJAAgFAHQgFAEgBAHIAoAAIAAAAg");
	this.shape_28.setTransform(55.475,10.65);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgXAqIAAhRIAWAAIAAALQAJgOAQAAIAAAWIgGgBQgGAAgFADQgHADgBAEIAAA1g");
	this.shape_29.setTransform(48.1,10.55);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgpA6IAAhxIAWAAIAAAKQAJgMAPAAQARAAAJALQALAMAAAUQAAAUgLALQgJAMgRAAQgPAAgJgNIAAAqgAgMgjQgEADgDAEIAAAcQADAEAEADQAGACAFAAQAJAAAFgGQAHgGgBgLQABgKgHgHQgFgHgJAAQgFAAgGADg");
	this.shape_30.setTransform(39.9,12.125);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgjA5IADgTIAHAAQAIABAEgHIADgGIgihTIAYAAIAUA5IAWg5IAXAAIgnBfQgFALgGAFQgIAEgMAAQgGAAgEgBg");
	this.shape_31.setTransform(25.9,12.35);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgKA5IAAhxIAVAAIAABxg");
	this.shape_32.setTransform(19.325,9.075);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AARA5IAAgyQAAgOgPAAQgLAAgHAIIAAA4IgWAAIAAhxIAWAAIAAAqQALgNARAAQAbAAAAAbIAAA5g");
	this.shape_33.setTransform(12.225,9.075);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgNAfIAAgqIgOAAIAAgTIAOAAIAAgXIAVAAIAAAXIARAAIAAATIgRAAIAAAkQAAAJAHAAQAGAAACgCIAEAQQgFAGgNAAQgWAAAAgXg");
	this.shape_34.setTransform(4.4,9.625);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AARAqIAAgwQAAgQgPAAQgLAAgHAJIAAA3IgWAAIAAhRIAWAAIAAAKQALgNARAAQAbAAAAAbIAAA5g");
	this.shape_35.setTransform(-3.475,10.55);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgfAeQgMgLAAgTQAAgRAMgNQAMgNATAAQAUAAAMANQAMANAAARQAAATgMALQgMAOgUAAQgTAAgMgOgAgPgQQgFAHAAAJQAAALAFAGQAGAHAJAAQAKAAAGgHQAFgGAAgLQAAgJgFgHQgGgHgKAAQgJAAgGAHg");
	this.shape_36.setTransform(-13.325,10.65);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AAoAqIAAgzQAAgNgMAAQgLAAgGAJIAAA3IgVAAIAAgzQAAgNgNAAQgKAAgHAJIAAA3IgVAAIAAhRIAVAAIAAAKQAEgEAGgDQAJgGAIAAQASABAEAPQAEgHAIgDQAIgGAJAAQAYAAAAAaIAAA6g");
	this.shape_37.setTransform(-25.575,10.55);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgXAqIAAhRIAWAAIAAALQAKgOAPAAIAAAWIgGgBQgGAAgFADQgHADgBAEIAAA1g");
	this.shape_38.setTransform(-39.9,10.55);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgfAeQgMgLAAgTQAAgRAMgNQAMgNATAAQAUAAAMANQAMANAAARQAAATgMALQgMAOgUAAQgTAAgMgOgAgPgQQgFAHAAAJQAAALAFAGQAGAHAJAAQAKAAAGgHQAFgGAAgLQAAgJgFgHQgGgHgKAAQgJAAgGAHg");
	this.shape_39.setTransform(-48.275,10.65);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgRA6IAAg/IgNAAIAAgSIANAAIAAgEQAAgOAIgIQAHgIAMAAQAOAAAIAIIgJANQgDgDgGAAQgKAAAAAMIAAAEIARAAIAAASIgRAAIAAA/g");
	this.shape_40.setTransform(-55.45,9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD4, new cjs.Rectangle(-124.9,-6.1,257.4,51.4), null);


(lib.HEAD2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMAMQgFgFAAgHQAAgGAFgGQAGgFAGAAQAHAAAFAFQAGAGAAAGQAAAHgGAFQgFAGgHAAQgGAAgGgGg");
	this.shape.setTransform(98.975,32.875);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AguAnIAMgUQAHAGAKAEQALAFAIAAQASAAAAgLQAAgGgKgDIgUgFQgggHAAgXQAAgOALgKQAMgKAUAAQAYAAASAPIgLAUQgMgNgTAAQgHAAgFADQgEADgBAFQAAAFAKACIAWAFQAfAIAAAYQAAAPgMAJQgMAKgWAAQgdAAgSgRg");
	this.shape_1.setTransform(90.85,29.075);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AglApQgQgQAAgZQAAgWAPgQQAQgRAXAAQAYAAAOARQAPAQAAAZIAAAGIhOAAQACALAHAGQAJAHAMAAQARAAALgKIAMASQgQAPgbAAQgYAAgQgPgAAbgJQgBgJgFgGQgIgIgMAAQgLAAgHAIQgGAGgBAJIAzAAIAAAAg");
	this.shape_2.setTransform(79.675,29.075);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgNBLIAAhpIAbAAIAABpgAgLguQgFgFAAgHQAAgHAFgFQAFgEAGgBQAHABAFAEQAFAFAAAHQAAAHgFAFQgFAFgHAAQgGAAgFgFg");
	this.shape_3.setTransform(70.775,26.85);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgeA2IAAhpIAcAAIAAAOQANgQAUgBIAAAcIgIgBQgHAAgIAEQgIADgCAFIAABFg");
	this.shape_4.setTransform(64.575,28.95);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AglApQgQgQAAgZQAAgWAPgQQAQgRAXAAQAYAAAOARQAPAQAAAZIAAAGIhOAAQACALAHAGQAJAHAMAAQARAAALgKIAMASQgQAPgbAAQgYAAgQgPgAAbgJQgBgJgFgGQgIgIgMAAQgLAAgHAIQgGAGgBAJIAzAAIAAAAg");
	this.shape_5.setTransform(54.075,29.075);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AggAoQgQgQAAgYQAAgXAQgQQAQgQAXAAQAcAAAOATIgSASQgIgMgPAAQgLAAgIAJQgIAIAAANQAAAOAIAIQAIAJALAAQAPAAAIgMIASARQgOAUgcAAQgXAAgQgQg");
	this.shape_6.setTransform(42.625,29.075);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgoAnQgPgQAAgXQAAgWAPgQQAPgRAZAAQAZAAAQARQAPAQAAAWQAAAXgPAQQgQARgZAAQgZAAgPgRgAgTgVQgHAJAAAMQAAANAHAJQAHAJAMAAQANAAAHgJQAHgJAAgNQAAgMgHgJQgHgJgNAAQgMAAgHAJg");
	this.shape_7.setTransform(30.675,29.075);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgeA2IAAhpIAcAAIAAAOQANgQAUgBIAAAcIgIgBQgHAAgIAEQgIADgCAFIAABFg");
	this.shape_8.setTransform(20.925,28.95);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgwA9IAMgUQAMAMAWAAQALAAAHgGQAKgGAAgPIAAgKQgNAQgTAAQgVAAgMgOQgOgOAAgZQAAgZAOgPQAMgOAVAAQATAAANAQIAAgNIAcAAIAABiQAAAbgTANQgPAKgWAAQgcAAgSgPgAgRgrQgHAJAAANQAAAOAHAHQAIAIALAAQAGgBAIgDQAGgDAEgEIAAgjQgEgFgGgDQgIgEgGAAQgLAAgIAHg");
	this.shape_9.setTransform(9.7,31.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgeA2IAAhpIAcAAIAAAOQANgQAUgBIAAAcIgIgBQgHAAgIAEQgIADgCAFIAABFg");
	this.shape_10.setTransform(-5.475,28.95);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgoAnQgPgQAAgXQAAgWAPgQQAPgRAZAAQAZAAAQARQAPAQAAAWQAAAXgPAQQgQARgZAAQgZAAgPgRgAgTgVQgHAJAAAMQAAANAHAJQAHAJAMAAQANAAAHgJQAHgJAAgNQAAgMgHgJQgHgJgNAAQgMAAgHAJg");
	this.shape_11.setTransform(-16.275,29.075);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgWBKIAAhRIgSAAIAAgYIASAAIAAgEQAAgSAKgKQAJgKAQAAQATAAAIAKIgKARQgFgFgGAAQgOAAAAAQIAAAEIAWAAIAAAYIgWAAIAABRg");
	this.shape_12.setTransform(-25.45,26.95);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgeA2IAAhpIAcAAIAAAOQANgQAUgBIAAAcIgIgBQgHAAgIAEQgIADgCAFIAABFg");
	this.shape_13.setTransform(-38.825,28.95);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AglAvQgLgKAAgQQAAgSALgIQALgIAOAAQAWAAALANIAAgNQAAgIgGgFQgHgFgJAAQgRAAgOANIgLgUQATgRAaAAQAVAAAMAJQAOAKAAAWIAABDIgcAAIAAgLQgMAOgVAAQgOAAgLgJgAgPAJQgGAFAAAHQAAAHAGAFQAGAEAIAAQAPAAAHgJIAAgNQgHgKgPAAQgIAAgGAEg");
	this.shape_14.setTransform(-49.525,29.075);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AglApQgQgQAAgZQAAgWAPgQQAQgRAXAAQAYAAAOARQAPAQAAAZIAAAGIhOAAQACALAHAGQAJAHAMAAQARAAALgKIAMASQgQAPgbAAQgYAAgQgPgAAbgJQgBgJgFgGQgIgIgMAAQgLAAgHAIQgGAGgBAJIAzAAIAAAAg");
	this.shape_15.setTransform(-61.225,29.075);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgtBJIAEgZQAEACAFAAQALAAAEgIIAEgJIgshrIAeAAIAbBKIAchKIAeAAIgyB7QgGAOgJAGQgJAFgPABQgJgBgFgBg");
	this.shape_16.setTransform(-72.975,31.25);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AglAvQgLgKAAgQQAAgSALgIQALgIAOAAQAWAAALANIAAgNQAAgIgGgFQgHgFgJAAQgRAAgOANIgLgUQATgRAaAAQAVAAAMAJQAOAKAAAWIAABDIgcAAIAAgLQgMAOgVAAQgOAAgLgJgAgPAJQgGAFAAAHQAAAHAGAFQAGAEAIAAQAPAAAHgJIAAgNQgHgKgPAAQgIAAgGAEg");
	this.shape_17.setTransform(-90.475,29.075);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgtA0QgPgVAAgfQAAgeAPgVQAQgYAdAAQAeAAAQAYQAPAVAAAeQAAAfgPAVQgQAYgeAAQgdAAgQgYgAgcAAQAAAwAcAAQAdAAAAgwQAAgvgdAAQgcAAAAAvg");
	this.shape_18.setTransform(88.575,5.075);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgoBCQgSgLAAgUQAAgNAJgKQAJgKAOgDQgdgLAAgYQgBgTATgLQAPgJAWAAQAXAAAPAJQATALgBATQAAAYgdALQAOADAJAKQAJAKAAANQAAAUgSALQgQAKgZAAQgXAAgRgKgAgQARQgKAGAAAIQAAAIAIAEQAIAFAKAAQAMAAAHgFQAJgEgBgIQABgIgLgGQgHgEgKgBQgIABgIAEgAgRgrQgHAFAAAHQABANAXAEQAZgEAAgNQAAgHgHgFQgHgEgLAAQgKAAgHAEg");
	this.shape_19.setTransform(75.1,5.075);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("Ag5A0IASgVQAPAQAYAAQALAAAIgGQAHgHAAgJQAAgJgHgHQgHgFgMAAQgSAAgMALIgWgGIAAhTIBkAAIAAAcIhFAAIAAAjQANgLATAAQATAAAOAMQAOANAAAVQAAAXgQAOQgQAOgaAAQgkAAgVgXg");
	this.shape_20.setTransform(61.925,5.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgPAVQAFgCAFgGQAFgGABgGIgEABQgGAAgFgEQgDgFAAgGQAAgIAEgEQAGgGAHAAQAHABAFAFQAHAHAAAKQAAAYgXAPg");
	this.shape_21.setTransform(52.4,12.25);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAFBJIAAhpIgXAZIgSgTIAtguIAcAAIAACRg");
	this.shape_22.setTransform(44.425,5.075);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgHBfIAAgUQghgCgUgUIARgYQAPAPAVAEIAAgjQgWgFgLgHQgPgLAAgUQAAgRANgMQANgMAWgDIAAgVIATAAIAAAVQAbAEASAQIgRAXQgMgKgQgEIAAAfQAWAFALAHQAQALAAAUQAAATgNAMQgMANgYACIAAAUgAAMAwQARgDAAgNQAAgJgRgEgAgXggQAAAIAQAEIAAgaQgQACAAAMg");
	this.shape_23.setTransform(33.725,5.05);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgRAoIAAg2IgSAAIAAgZIASAAIAAgdIAbAAIAAAdIAWAAIAAAZIgWAAIAAAvQAAALAJAAQAIABACgEIAGAVQgHAHgQAAQgdAAAAgdg");
	this.shape_24.setTransform(17.7,5.75);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AglApQgQgQAAgZQAAgWAPgQQAQgRAXAAQAYAAAOARQAPAQAAAZIAAAGIhOAAQACALAHAGQAJAHAMAAQARAAALgKIAMASQgQAPgbAAQgYAAgQgPgAAbgJQgBgJgFgGQgIgIgMAAQgLAAgHAIQgGAGgBAJIAzAAIAAAAg");
	this.shape_25.setTransform(7.925,7.075);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgxA8IANgUQAMANAVAAQALAAAIgFQAKgIAAgOIAAgLQgNARgTAAQgUAAgOgNQgNgPAAgZQAAgZANgPQANgOAVAAQATAAANAQIAAgNIAcAAIAABiQAAAcgTAMQgPAKgXAAQgbAAgTgQgAgQgqQgIAHAAAOQAAAOAIAHQAGAHAMAAQAHAAAGgDQAIgEADgEIAAgiQgDgFgIgEQgGgDgHAAQgMAAgGAIg");
	this.shape_26.setTransform(-4.95,9.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAVA3IAAg/QAAgVgTAAQgNAAgKANIAABHIgcAAIAAhqIAcAAIAAAOQAOgQAWAAQAjAAAAAhIAABLg");
	this.shape_27.setTransform(-23,6.95);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AglAvQgLgKAAgQQAAgSALgIQALgIAOAAQAWAAALANIAAgNQAAgIgGgFQgHgFgJAAQgRAAgOANIgLgUQATgRAaAAQAVAAAMAJQAOAKAAAWIAABDIgcAAIAAgLQgMAOgVAAQgOAAgLgJgAgPAJQgGAFAAAHQAAAHAGAFQAGAEAIAAQAPAAAHgJIAAgNQgHgKgPAAQgIAAgGAEg");
	this.shape_28.setTransform(-35.625,7.075);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AggAoQgQgQAAgYQAAgXAQgQQAQgQAXAAQAcAAAOATIgSASQgIgMgPAAQgLAAgIAJQgIAIAAANQAAAOAIAIQAIAJALAAQAPAAAIgMIASARQgOAUgcAAQgXAAgQgQg");
	this.shape_29.setTransform(-46.625,7.075);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgxAVIAAhKIAcAAIAAA/QAAAUAUAAQANAAAKgNIAAhGIAcAAIAABpIgcAAIAAgOQgPAQgWAAQgiAAAAghg");
	this.shape_30.setTransform(-64.225,7.225);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgoAnQgPgQAAgXQAAgWAPgQQAPgRAZAAQAZAAAQARQAPAQAAAWQAAAXgPAQQgQARgZAAQgZAAgPgRgAgTgVQgHAJAAAMQAAANAHAJQAHAJAMAAQANAAAHgJQAHgJAAgNQAAgMgHgJQgHgJgNAAQgMAAgHAJg");
	this.shape_31.setTransform(-76.925,7.075);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgOBJIAAg8Ig5hVIAkAAIAjA6IAkg6IAkAAIg5BVIAAA8g");
	this.shape_32.setTransform(-88.3,5.075);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD2, new cjs.Rectangle(-139,-7,278,48), null);


(lib.CTA_mobile = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgzBwIA7hwIg7hvIAsAAIA7BvIg7Bwg");
	this.shape.setTransform(23.7,0.575);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgcAfQgNgMAAgTQAAgRANgMQALgNASAAQASAAALAMQAMANAAATIAAAFIg8AAQABAIAGAFQAHAGAJAAQANgBAIgHIAJANQgMAMgVAAQgSAAgMgMgAAVgHQAAgHgFgEQgGgGgJAAQgJAAgFAGQgEAEgBAHIAnAAIAAAAg");
	this.shape_1.setTransform(8.6,7.95);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgXAqIAAhRIAWAAIAAAMQAKgOAPAAIAAAVIgGgBQgFAAgGAEQgGACgCAEIAAA1g");
	this.shape_2.setTransform(1.275,7.85);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgfAeQgLgMAAgSQAAgRALgMQAMgNATAAQATAAANANQALAMAAARQAAASgLAMQgNANgTAAQgTAAgMgNgAgPgQQgFAHAAAJQAAAKAFAHQAGAHAJAAQAKAAAFgHQAGgHAAgKQAAgJgGgHQgFgHgKAAQgJAAgGAHg");
	this.shape_3.setTransform(-6.975,7.95);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAoAqIAAgyQAAgNgMgBQgLAAgGAKIAAA2IgVAAIAAgyQAAgNgMgBQgKAAgHAKIAAA2IgWAAIAAhRIAWAAIAAALQAEgFAGgDQAJgFAIAAQARAAAEAPQAFgGAHgEQAIgFAIAAQAYAAAAAZIAAA6g");
	this.shape_4.setTransform(-19.1,7.85);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AARAqIAAgwQAAgPgPgBQgLAAgHAKIAAA2IgVAAIAAhRIAVAAIAAALQALgNAQAAQAbAAAAAbIAAA4g");
	this.shape_5.setTransform(8.4,-6.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgXAqIAAhRIAWAAIAAALQAKgNAPAAIAAAVIgGgBQgFAAgGAEQgGACgCAEIAAA1g");
	this.shape_6.setTransform(0.875,-6.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgcAlQgJgJAAgMQAAgNAJgHQAIgFALAAQARAAAIAJIAAgKQAAgGgEgEQgGgEgHAAQgNAAgKAKIgIgPQANgNAVAAQAQAAAJAHQALAIAAAQIAAA0IgWAAIAAgJQgJALgQAAQgLAAgIgGgAgLAHQgFADAAAHQAAAFAFAEQAFADAGAAQALAAAFgIIAAgKQgFgHgLAAQgGAAgFADg");
	this.shape_7.setTransform(-7.4,-6.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgcAfQgMgLAAgUQAAgRALgMQANgNARAAQASAAAMAMQAKANABATIAAAFIg8AAQABAIAGAFQAHAGAJAAQANgBAIgHIAJANQgLAMgWAAQgSAAgMgMgAAVgGQgBgIgEgEQgFgGgKAAQgIAAgGAGQgEAEgBAIIAnAAIAAAAg");
	this.shape_8.setTransform(-16.4,-6.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgjA5IAAhxIAYAAIAABbIAvAAIAAAWg");
	this.shape_9.setTransform(-25.2,-7.65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.CTA_mobile, new cjs.Rectangle(-47.5,-17.2,76.4,36.8), null);


(lib.coahreveps = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// coa-h-rev.eps
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgqAsQgTgRAAgbQAAgZATgSQASgSAYAAQAaABASASQASARgBAZQAAAagRASQgSARgaAAQgYAAgSgRgAgngmQgQAPAAAXQAAAXAQARQARAQAWAAQAXAAARgQQAQgQAAgYQAAgWgQgQQgQgRgYAAQgXAAgQARgAAPAmIgFgWQgCgIgEgCQgDgCgHAAIgFAAIAAAiIgOAAIAAhMIAZAAQAMAAAFABQANAFAAANQAAAPgQAEQAFABACAEQADADABAIQADAQADAGgAgLgHIALAAQAQAAAAgKQAAgHgGgDQgCgBgKABIgJAAg");
	this.shape.setTransform(361.0507,13.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACIJCQgIgCgLABIgTACQAAgCgIgCIgLgBQgOABgGgCQAAgCgPABIgdgBQgKgCgGAAIgPgBIgPgCIgNABQgOABAAgDIgMgDQgHgDAAAGQgCAAgEgCQgEgDgDAAQAAAEgHAAIgLgDQgLgBgIABQgNABgVgIIgHgDQgDgCgEABQgCABgMgJIgKABIgKAAIgKACQgDAAgDgEQgDgEgCAAIAAAEQgDAAgEgCQgFgDAAgDIgCAFQAAgCgHgDQgGgCgFAAQAAABAAAAQAAAAAAAAQAAAAAAAAQgBAAAAAAIgBAAQgCABgEgDQgEgDgDABQgBABgBAAQAAAAgBgBQAAAAgBAAQAAgBAAgBIgGgFQgGgDAAADQgCAAgKgEQgKgEAAgCQgMgIgEAAIAAADIgEABQABADgNgGQgCgCgEAAQAAgFgCgCIAAAGIgEgDQgBgBgBAAQgBAAgBAAQAAAAgBAAQAAAAAAABIgGgHIgMgBQAAgCgLgFQgLgFAAgCQgIgEgCgHQgBgDgHAAIgMgCIgQgIIAAABIgFgCIABgCQgFAAgKgIQgJgGgDgHIgJgDIgCgDQAAAAgBgBQAAAAgBAAQAAAAgBgBQgBAAgBAAIgEgLQgDgBgCACQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAAAQgBgJgQAAIghgDQgQAEgEgBQAAgCgUAAQgVAAgCgBQAAACgTgEIgGABQgEABgBgBIgMgDQAAABgFAAIgGgBQgDAAgEgCQgDgBgEAAIgMAAQAAACgLgEQgFAAgDgFQgCgBgLAAIgKABQgDABgXgDQgXgDAAgBQgJgEgGAAIgTgCQgCgDgWgGQgWgFAAgBIgEgCQgDgCgDABQgLADAAgEQgHgEgMAAQAAgEgJgBQgKgBgBgBQgKgDgDgDQgGgFgNgCIgUgDQgDgEgCACIgGACIgFgDIgFgCQAAgDgHgBQgIgBgBgEIAHgBQgBgEgKgDQgJgEAAABIgQgHQgEAAgGgEIgJgGQgLgFgKAAIARARQAAADAGAFQAGAFABADIAIAHQAEAGADABQAIABAEAGQADAAAFADIAIAEIAGADIAGAFIAKADIAIACIADACQABAAAAABQABAAAAAAQABAAAAAAQAAABAAAAQAFAAAEAFQACAEASADQASAEAAACIATAIQADAAAEADQAFADADAAIAgAIQADAAAGAEQAGADADgBQADgBAHAEQAJADACAAQAAgBAOAEIARADQAHAAAPAFQAAACAYACQAAAEA/AFQACACAdADQAcADAAABIBBAFIAgADQAcADAAgBIAHABQgGAAgJAEIgQAGIgKgCQgJgBAAACQgFADgFgCQAAAFgQABQgQABAAgDQgNACAAgCIgEABQgBABgBAAQgBAAAAAAQAAAAgBgBQAAAAAAgBIgIgBQgDgBgDgFQAAABgBAAQgBAAAAAAQgBABAAAAQAAAAgBABQgBABgEgBIgLAAQgTgCgDgBIgEgEIgHAAIgKgDQgIgCAAACQgHAAgGgCQgCgFgDABIgHAFQgEACgFgBQAAgDgJgBIgLgBQAAADgogIQAAgCgMgBQgMgBgBgDQgGAAgJgCIgPgEQgBgBgLgBQgLgBAAgBQgFAAgHgCIgLgEQgVgFAAgCIgLgBQgIgCAAgCQgFAAgNgFQgBAAgBAAQgBAAgBAAQAAAAgBgBQAAAAAAgBQgIAAANAJQACACAFACQAEABADADIAIACQAAADAJAAQAAABAPADQAAACAVAEQAVADABAHIgIABQAAgCgTgDQgUgCgCgDQgngKAAgEIgUgHIgQgGQgXgGgHgJIgHgEQgHgEAAABQgCAAgGgEQgGgEAAgBQgIAAgNgHQgOgHgCgIQgMgIgFAAQgIgKgFgCQgFgFAAgCIgHgDQgFgCAAgDQgFgDgGgHQgFgGgDgGQgCgBgEgFQgEgGABgCQgDAAgCgHQgDgIgDAAQAAgDgDgFQgDgFAAgEQgBAAgEgQIgFgTIgGgdQgFgdADAAIgDgRQgDAAAAgUQgCAAgBgLQAAgLgBgBIgIhEIAAgaQAAgXACAAIgCgdQgBgaAEAAIgDgpQgBgjAFgDQAAgDAIgVQAIgVAAgDQAHAAAFgLQAGgNAEgCQADgBACgEQACgFACgBQAAgEAFgFQAFgEAGgBIgCgEQAAAAAAAAQAAgBAAAAQAAAAABgBQAAAAABgBQAEgBAAgCIAGgGIAIgGQAEAAADgBQAJgHgFAAQgCgFAFgEQAEgDAEAAIAGgDIAHgCQAIgDAIgIIANgOIAIgGIAEgCIACgEQABAAALgIQAAgCALgEQALgFAAgDQADAAAHgGQAIgFABgDIALgHQAGgDAGAAIAKgFIAHABQAFABABgCIASgDQAMgEAAgHQADgBABgDIADgEIAEgEIAEgEIgBAAQAAgEAFACIAIACIAOgCIAHgEIAIgEIAHgDQAGgEACAAIADgCIADgCIAIgBQAGgCAAgDQgFAAAFgFQAFgFAEgBIAKgGQAFAAAFgDQAAgCAFgCQAFgBAAgDQAFAAAAACQAFAAAGgDIAJABQAFABABgCIALgGQAIgEADAAQAAgCAJgCIAMgDIAGgBQAGAAAAgBIAJgBQABgCAAgGQAEgBAEgEQADAAAEABIgBAEQADAAADgDIAAAAIAAAAIAAgDQAaAAAFgBQAFgCALAEQAKgFgEAAQgDgHAQgFQAPgFAAAEQALgHAUAAQABgDAIABQAHABACgEIASgDQAQgDAAgBIACABIAlgIQARAAAAgEIAHgBIAGgCIAagFIAngGQALAAAagFQAagEAOAAQAAgDAegBQAdgBAGABQAAABAGABQAFABAAACQgHAFgSgCIgOAAIgNABQgIAAgOADIgWACQAAgBhHAPQAAAEAjgEIAogFIAmgEIAWgDQAOgCAHACQAAgBAJAAQAIABAAAGQAPAAAAABIAGAAQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAIgGAAQAAADgsABQAAABgOACIgQACIgQAAQgPABAAACIgoAGIgeADQAAACgLACIgMABQgHAAgMAEQgNADgGAAIgKACQgKABAAACQgDAAgFADQgFAEgDAAIgPgBQAAACgNACQgNACAAADQgCAJgJACIgSACQAAACgHADIgKADQgEAIgHAEQACAHAcAAQAZABAGgDQADgCAUgDQATgDAAgCIAKgBIAKgCIAFAAIAGABQANgDAIAAQAAgBAXgDIAXgEQADAAAWgEQANAAAXgDQAAgBAfgDQAggCAEABIAhgCQAegCAAABQAKgBATABIAYgBQAPgBAIACQAAACAIACQAIACAAgCIAMABQAAAAAAgBQAAAAABAAQAAAAAAAAQAAAAABAAQAAAAAAABQABAAAAAAQAAgBAAAAQAAAAAAAAIALABQAJACAAACQgEABgSABIgRAAIgfABQgCADgSAEQgRAEAAACIgNgBQgMgBAAACIgTAAQAAAEgUAAIgZAAQAAACgeABQgeACgBAGQAOACASgCIAggFQAAACAegCIAdAAIANgCQADAAADACQAEACAEAAIANgBQAIABgEAFQgEAGgbACIgbACQhGAEAAACIgQACQgPABAAgBQgGgBgHACIgMADIgOABQgBACgFAAIgJAAQgEAAgHAFQgHAFgFABQAAACgLACIgNADQAAABgGACQgGACAAABIgPADIgJABQgJACgBABQgNAAgKAKIgNAFQgJAFgFABQAAgBgKAEIgNAFQAAgBAAAAQAAgBgBAAQAAAAgBAAQgBAAgBAAIgFACIAEABQgDAEgIAAIAAgDIgGACIgFACQAIAHgQADQgTADAAACIgQAFIgPAEQAAgBgSAGIgVAHIgNAFQgOAFgCACQgQAAgCADQgEABgFADQgGAEgEgBQgFAAgEAEQgFAFgEAAQgCgCgEABIgHAEIgIAEIgIACQgBABgJACIgKACQAAAEgIACIgLACIgDACQgCACgDAAQgEAAgBADQgCADgDACIgCACQgBAAAAABQAAAAgBAAQAAAAgBAAQgBAAAAAAQgCgCgEgBQgBAAgBAAQgBAAgBAAQAAABgBAAQAAABAAAAQgDAAgCAFQgBAFgCABQAAADgIAAIgNAHQAAABgKACQgJACAAADIgKAGQgGAEAAACIgIAEQgFADgEABQgHAFgCAAIgQAHQgEADgEAAIgNAKQAAADgGADQgGAEAAACQgHAEgKABQgBADgDACIgFADQgEAAgDAGQgEAGgDABIgJAGQgHAEgCAAQAAAFgFACQgHADgBAEQgSAMgGAIQgEAAgEAFIgHAIIgEAFIgFAEQAAACgFACQgEACAAADQgBAAgGAHQgFAHgCAAIAAADQgEAAgEAFIgGAIIgGAHIgGAHQgCAGgJAKQgHAKgCAHQADAAAFgFIAIgIQAFgJADAAQAAgDAGgDQAFgEAAgDQgBAAAIgHIAJgHQAFAAADgHQADgHADAAIAFgGQAFgEACAAQACgDAFgEIAJgFQAAgCAEgDIAFgFIARgMQADgHAQgEQABgCAHgEQAHgDAAgBQgBgDAFgCIAGgDQADgBAQgLQADAAAEgDQAFgEACAAQAAgBAbgPQAGgCANgGQAPgIAAgCQAHgBACgCQAAAAABAAQABgBAAAAQABAAAAgBQAAAAABgBQAAAAAAgBQABAAAAgBQAAAAABAAQAAgBABAAQAFgBACgBIAGgEIAEgDIAEgDIAFgCQAAAEAUgMIAGgCQAEgCAAgBQAGAAALgIQALgGAGAAQADgEAHgBQAHgCADgDQADAAAFgDQAEgDADAAQAEgEAHAAIAHgGIAKgBQALgGAEAAIAFgCIAGgCQACgDAIgBIAJgBIAHgEQAGgDAAgCIANgCQAAgDAJgCIALgCQAAgEAKgBQALAAACgDIAhgJQAcgIAAgEQADAAAOgEQAPgFAAgBIALgBQAIgCAAgDQAqgFAAgDQAIAAAOgFIAVgGQAAgBATgEIAWgEQAAgBAYgFIAbgGQAHgBALgBQAAAAAAAAQAAAAABgBQAAAAABAAQABAAABAAIAFgBIAQgEQAKgCAGABQAAAGgSAEIgZAEQgNADAAACQgDAAgGAFQgFAEgFgBQAAgBAAAAQAAAAAAAAQAAAAgBgBQAAAAgBAAQAAADgUAGQgHAHgFAAQgDADgFAAIgJACQgdAKgRACIgDADQgDACAAACQgEAAAEADQABABABAAQABABAAAAQABAAAAgBQAAAAAAgBIAKgBQAJgBAAgCQAZAAgNAFIgLAHQgCACgFgCQgEgBgBAFQgHgBgHADQgIADgHAAQgEAAgFAEQgGAEgDAAQAAACAFAAIALgDQAAAKgfADQgBACgFABQgDACgDgBQgDAAgDABIgGADIgHACQgDAFgQAAQgIABgCAEQgDAAgDACQgBAAAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAQgDgCgCABIgEAEIgGADQgMADAAADQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAAAAAIAAACQgGADgEgBQAAAFgIABIgMgBQAGAFgGACQgEABgFAAQAAgBgNAHQgDAFgMAAQAAAAgBgBQAAAAAAAAQgBAAgBAAQgBAAgBABIgDACQAAgBgBAAQAAAAAAAAQgBAAAAABQgBABgBABIgEAFIgFgBQgBAAAAAAQgBAAAAAAQgBAAAAABQAAAAAAAAQgFADgGAAQgEgBgJACQgLACAAADQgCAAgEADQgEAEgDAAIgWAHQAAADgDACQgDAAgDACIgFABQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBABIgFABQgEAAgDADIgGAEIgFADIgEADQAAAFgJABIgLABQAAABgEACIgGACQgDABgFAHQgEAGgFgBQgGgCgHAHIgIACQgGACgBACQgGABAAAFIgHAAQAAAAABAAQAAAAAAABQAAAAAAAAQgBABgBAAIgEAAQAAAAgBAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAABgBAAQAAABgBAAQAAABgBAAIgFABQgCgCgEACIgIAEQgNAFgIAJQgHABgGADIgNAHQAAAEgJAFQgLAGgBADIgIAEQgFABAAAEIgJADIgGACQAAAAgBABQAAAAgBABQAAAAAAABQgBAAAAABQAAABgFADIgEADIgEAEQgCAAgCADQgDADgBAAQgGABgDADIgLAMQgGAHgIADQAAAEgLAHQgLAJAAAFQgEACALAJQANAKgBADQgEAAgFAJQgEAIAAAFQgDAAANAKQAMAKAAgDQAEAAAHAFQAHAGAAAFQABAEAHABQAJACACABIAJAHQAFABAJAFQAJAEAFAAQAAAGAjAAQALAJAGAAIAGABQAHABABABQAPAAAEADIALAIIAHACQAGACACgBIARgEQADADACAAQAAABAAABQgBAAABABQAAABAAAAQAAAAABABQABABALgBQAKAAABADIAQABIAHABIAHABQAAgCAMACIAPADQADgEAFAAIAIABQABABAGAAQAGAAACACIAEAJQADAGADAAIABgBIABgBIABgLQAAgEAFAAIAIAAQAAABAaABQAAgCAIADIAKADQAAgEAIgBQAIgCAAAGIAmgEIgBgCQADgCgDgNQgDgMABAAIgEgLQgDgJABAAIgBgGQAAgBAAAAQgBgBAAgBQAAAAgBAAQAAgBAAAAIgBgQQAAgaAEAAIgBgCQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAAAAAgBQACAAACgJIABgLQADAAACgPQAAgDADgGQADgFAAgEIAHgZIAGgOQAEgHAAgGQAEgBACgFQACgHACgBQAGgGgBgFQAKgKgBAAIAEgFIADgFQgBgEADgBQAAgBAEgFQAFgEAAgDIAGgGQAEgFABAAQAAgCAEgDIAHgFQACAAADgDIADgFQAMgGAKgLIAFgCQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABQgJAGgFAFQgEACgEAGQgEAFgBAFQAFgBADgDIAFgGQAMgFAAgBQAGgBALgIQAJgIAIAAQAIAAAEgDQAAgBAAAAQABAAAAgBQABAAAAAAQABAAAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABgBQAAgCAIgGQAFgFAFgDIAHgEQAEACADgBQABgBAEgBQABAAABAAQAAAAABAAQAAAAAAgBQABAAAAgBIAGgFQAFgEAAACQAFABAAgIQAEgBABgBIAEgDIAKgDQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBABgBQAAAAABgBQAAAAABgBQAAAAABAAQAAgBABAAQAAgBAJgFIALgGIACgEQAAAAAAAAQAAgBABAAQAAAAABgBQABAAABAAQAFgBAFgFQADAAAFgCQACgDAHgDQAGgCADgDQADgDADABIAEADQACAFgMAGIgPAHQAAABgGAEIgIAEIgKAHQgHAEgBAEQgDABgHAFQgGAFgFABQAAAGgKACIgJAHQgFAEgCAFQgGACgGAGQAAAAgBAAQAAABgBAAQgBAAAAAAQgBABAAAAQgCACgEAAQgFABgCAFQgGAEgCAHIgNANIgMAJQgJAGAAAFQgKAGACAKIgDAEIgCAEQgDACgBAIIgKAIQgHAIAAgDQgCAAgBAGQAAAFgHAAQAAADgHAFIgBAIIgFAIIgEAIIgKAJIgCAFIgBAFIgEADQgBABAAAEQgBAAgDAFIgDAIQgCABgEAGIgFAGQAAAPgHADQgFACABAIIAAAKQgEAAgBAVQgBAUACAAQAAgIAHgKQAIgMABgGQACAAAEgGQAEgFAAgCIAIgRQACgBAEgGQADgGAEAAQAEgNAIgBQgCgIALgFIAKgMQABgDAHgHQAHgGAAgEQAFgBAEgHQAEgHAEgCQAAgCAJgIIAMgIQAAgDAIgGQAJgFAAgCQAFgDAKgKIANgLQADAAADgEQACgFADAAQABgDAHgFQAFgEAEgBQABgCAEgDQAFgDABgCQAGAAAKgKQAJgKAGAAIAIgFQAGgEAAgCQABAAAAAAQABgBAAAAQABAAAAgBQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABAAABAAQAGgBgBgEIAEAAQAAgBAOgHIARgIQAAgDAPgJQAPgIAEAAQAGgIAQgFQAAgBAIgEIAJgDIASgIQAPgHAAgBIAEgDIADgDIAJgBQAAgCAGgCIAGgCQADgCAGADQACgIAFAAQAFgFAGAAQAAgBAGgCIAIgCQAEgGAUgFQABgBAFgCQAEgBACgCIAFgBIAGgCQAAgCAFgBIAEgBIADACIAZgMQAAgBAKgDQAIgCAAgBQATgGAAgBIAIAAQAFAAACgDQACAAAGgEQAHgDAAgBQABAAABAFQAAgDAHgDQAFgDAFAAIASgGQANAIgDgGQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAgBAAAAQgBgBAAAAQAAAAABAAQAAAAAAAAQAAgCAmgHQACgDASgDQATgEAAgBIAGgCIAGgCQAAgCAOgBQAQgCABgBQACAAACgDQADgCACAAQAAgCAJAAQAggGADABQAAgCARgDIAVgDQAGAAALgCIAQgFQASgEAIAAIA2gIIAZgEQAQgDAJAAQAAAAgBAAQAAgBAAAAQgBgBAAAAQAAgBAAAAIAIADQAHADAAgFIAQgBQAzgGAAACIAMgCQALgDAAABIAcAAQAZgBAAgBIBRgBQAAgCAhADIAoADIAIAAQACADADgBIAHgCQABAFgCAAQgBAAgBAAQAAAAgBAAQAAABAAAAQAAAAAAAAQgFADgKAAQAAAAAAAAQAAAAgBAAQAAgBgBABQAAAAgBAAIgFABQgCAAgDgCIgEgBQgLAGAAgEQgNABgHgBQAAgCgTAEQgJgBgIABQgCAEgFgBIgIgDQAAADgJAAQgIgGgCACIgDACIgEABQgCADgFAAQgDABABAFQgKAAgCAHQgCAHALAAQABACAIAAQAIABADACQAAgEAGACIAHADQAAgBAAAAQABAAAAgBQABAAABAAQABAAABAAQADgBADABQACABABAAQABAAABAAQAAABAAAAQAAAAAAAAIgFADQgBACgIAAIgKgBIgFABQgFABgBAEQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIgCADIgPABQgIADgGAAIgiACQgCAEgJAAIgOAAIglABQgyAHgGgBQAAAEgpAAQAAABgGACIgIACIgLAAIgJACQgEgBgLADIgcABQAAABgRADQgRADgDAAQAAgCgJAFQgIAFAAACIAbAAIAWgDIAPABIAHgBQAEgCADAAIAMgCQAKgCAAACQAFABAGgFIALABQAAAEAJgGIAWgDQAAgCAHAAIAJABQAFACAFgCQAFgBAEABQAAgCAOgDQAOgDAAAEQAjAEAAgCIAHAAQAGABAAADQABABgGACQgGADgCgBQgEgBgJABQgJABAAADQAegEA1ACIAgADQAUADALAAQAfAAAtAIIATADQAQADAAADIAXAEQAVAEAAACIAHAAQADAAABgDQAFgCAGAAQAFAAAEABQAAABAGACQAGACAAABQAQAAAVALQAMAPgBAAQAAAFAPAAIgJgIQgHgGAIAAQAFAAAHAEQAIAEADAAQAjASADAAQAAABAMADQAMADAAADQADAAAGACIAIADQAAABAhALIAUAMQAPAJAAAGIAIAEQAAADAIAGQAHAGAAADQAFAJACAAQAAADAEAFQADAFAAADIADAGIABAHQAEAAAEAQQADAPADAAIAHARQAEAJAAAJQADAAADAWQACAAAFATIALApQAMAogDAAIAEAmQABADgCAEIgCAGQgCAAAAAGIABAHQgCAAgCAGIgDAIQgCABgEAMIgFAMQgBAEgEgBIgBAFQgBAAAAAAQAAAAAAABQgBAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAAAAAAAQgBAAAAAAIgGABIAAACQAAABAAAAQAAABAAAAQgBABAAAAQgBAAAAAAQAAAAgBABQAAAAAAAAQAAABgBAAQgBAAAAAAQgEABAAAFQgCABgDAEQAAABgBAAQAAAAAAAAQgBAAAAgBQgBAAAAgBQgGAAgEAFQgEAAgBAGQgBAHgDABQAAAFgEADQgFACgFgBQABAKgHgCQgKgDgCADIAAAKQgCAAgCADIgCADIgDABIgCACIAAAFQAAAAAAABQAAABAAAAQgBAAAAABQgBAAAAAAQgHgCAAABIgJADQgCAAgDADQAAAAgBABQAAAAAAAAQgBABAAABQAAAAAAABQAAABAAABQAAABAAAAQAAABABAAQAAAAABAAQgCAJgKAAQAAgCgHgCIgJAAIgFABQgFACAAACQAAACgEABIgFACIgLAEQgJAFAAACIgMAGQgLAGAAABQgEACgCAGQgCAEgGgCIgCAFIACADIACAFQgGABgIgCQgJgCgEAAIABAJQAAAEgFAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQgBAAAAAAQgBABAAAAQgBABAAABQAAAAAAAAQABABAAAAQADABABADQgDACgEAAIgIAAIgIgEQgFgEgEAEIgDAFQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAgBAAIgFADIgFADQgBAEgHAAIgMgBQAAAHgHABQgKADgCACQgDAGgCgCQgBgCgDgBQgBAAgBAAQAAAAgBABQAAAAAAABQAAAAAAABQgBAAgBAAQgBAAAAAAQgBAAAAABQAAAAAAAAIgBAFIgJABQgDgBgFAEQgDADgDgGQgCAAgDADQgCAEAAADQgEAAgEACQgEADAAADIgFAAIgGABIgBAAIgCAAQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAQgCABABAEQAAAAAAABQAAAAAAAAQAAAAAAAAQAAABAAgBIgEAAQgJADgEAAQgEAFgGABIgMACQAAAAAAAAQgBABAAAAQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBADACAFQAAADgLgDIgGAEQgFAEAAACIgIgBQgDAAgCAFIgIADQgFABgBgDIgLAGIgKAHQAAAFgOgDQgPgCAAAGIgEgBQgBgBAAAAQgBAAAAAAQgBAAAAABQgBAAAAABQgBAAgCAEQgBABgBAAQAAABgBAAQAAABgBAAQAAAAAAgBQAAAAAAAAQgBgBAAAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIgFAGQgDADgEAAIgDAAIgEABQgBABAAAAQgBAAAAAAQAAABAAgBQgBAAAAAAQAAgBAAAAQAAAAgBAAQAAgBAAAAQAAAAgBAAIgFAEIgHADQgFACABACIATgBQAMAAAGgDIAagFQATgEAAgCQADgBAEAFQADAFAEgCQAAgBANgDQACgEAVgDQAAgBAIgCIAKgDQAQgBgBgEIAJgDQAFgBABAEIAMgFQAJgCAFAAQgOAJgFABIghARQAAgFgHABQgIABgCAEIADACQgEAAgPAGQgRAGAAADIgIABQgGABAAACQgFABgDgBIgIgCQgBAIgFAAIgMgBQAAACgHAAQgHAAABADQgRAIgFABQgSADAAABIgHAAQgFAAAAgBQgCgBgDABIgGACQgSAJAAgGQgDgBgDACQgEACgBACQgCgBgHACIgFADIgRAEQgFAAgEADQgFAEAJABQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIACABQAAgCAOgBQANAAAAgCQAGAAATgFIAYgDIAdgFIASgEQAPgDAAABQAHAAAJgEIAPgFQgBgCAMgDIANgEIARgGQANgFADAEQgfAOAAgBQgFABgJAFQgJAEgEABQABADgIABIgLACQgIAEgJACQAAgCgKAHQgBAEgDgEIgDgCIgHADQgEADgCAAIgJADQgHABAAACQgEAAgFABIgKACQAAAJgJgMQgBAGgBAAQgDgEgHACQgHACgCAAQgFAFAAACQgEAAgDgCQgFgDgDgBQAAAFgFACIgJAEQgTAJgKgJIgMADQAAAGgNAAQAAACgJACQgKACgDAAQAAgEgHAAIgJABIgDAFIgFgBQAAACgSgBQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAAAgBAAQAAADgHAAQAAgGgDAHIgCAEIgHACQAAgCgFAAQgEAAgDACQgCABgNAAQgLAAgBACIgUAAQgEAAgGgCQgGgDgDAAQgGAGgHAAIgOgCQAAABgIABIgIADIgNACQgJABgEgDIgLAAIgOgBQAAAEgFgBIgIgCQAAACgMABIgGABQgHAAAAgDgAB5IPQAAAAAAABQABAAAAAAQAAAAABAAQABAAAAAAIAEgCIAYgCQAUgCABAEIADgDQACgCACgBIAGAAQADgBAGABIAHgBIAMgEQAIgBAFADQABgFADADIAEADQADABAEgFQADgEADAAIAGACQACAAAEgDQAEgCAIAAQABgBAAAAQABAAABAAQAAAAABAAQAAAAAAABIABAEQADgBAEgEIAHgDIAPgDIAJgCQAFAAAEgCQAHgFAEAAQgEgBgMAEIgPAFIgaACQgRACgNgBQggAGgBgEIgLACQgJACgHgCQgJgBgKABIgsACQgEABgBgEIgIADQgBgCgFgCIgIgCIgGACIgGAAQgIgCgXgBIgVgBQgQgCgHAAIgKAAIgIgCIgCACQAAAAAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAgCgEAAIgGgBQgIgCgUgBIgLgCQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAABgBAAIgCABQgJABgHgCIgEgDQgBAAAAAAQAAgBgBAAQAAAAgBAAQgBAAAAAAIgLAAQAAAAgBAAQAAgBAAAAQgBAAgBAAQAAAAgBAAIgGAAIgGgBIgGAAIgFgCIgGgDIgMgCQgHgCgEgDQgDgDgBAAIgFABIgIgBQgFgBgEABQgBgDgJgDIgMgBQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAQgHABgIgFIgOgFQgNgGADgBQgCgBgFAAQgEABgDgCQgHgDADgBIgOgFQgCgBgMADQgOACgMAAIAiAYQANgBAKADIAKADQAIAAAJAFIAKAEQAIADAAACIAGgCQABAAAAAAQABAAAAAAQABABAAAAQABABAAAAIAEAGIAJgCQAHAAABABQAAABAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIAOAFQAFADAJgBIAOAFIAHACIAIABQANAEAdADQAyAJAuAEQAoADAGABIAaAAIAMABIANABIAKAAQAHgBADABQAAABABAAQAAAAAAgBQABAAAAAAQABAAAAgBIABAAIACACgAE4GhQAAABABAAQAAABABAAQABAAAAAAQABAAAAAAIgBgGQAAgCAGgBQABABAFAAIAHgCIAMACQAJACAAgEQAEgFAHADIAKAGQABAAABAAQABAAAAAAQABgBAAAAQAAAAAAgBQAAgDACgCQAEgCACAAQAAAAAAABQABAAAAAAQABABAAAAQABABAAABQAGgHAOgBIAVABIAEgCIAEgDIAIAAIAGAAQAAgCAMAAQADAFACAAQAAgEAHgBIAGgBIAPgDQAAAAAAAAQABgBAAAAQABAAAAAAQABAAABAAQAAAAABAAQAAgBABAAQAAAAABgBQAAAAABgBQAJgEAGACIASgCIAEABQABAAAAAAQAAAAABgBQAAAAAAgBQABAAAAgBQAAgBAAgBQAAAAABgBQAAAAABAAQAAAAABAAQABAAAAABQABAAABAAQAAAAABAAQAAAAAAAAQAAgCAMgCIAOgCQABgCAMgEQAKgEADAAQADAAADgDQAEgCACAAQAAgCAGgBIAHAAQAGABAJgGQAFAAAIgEQAJgFAFAAQABgCALgEIAPgEQABgCAKgCQAJgDAAgBIARgGQACAAAEgCQADgCADAAIAJgDIAFgDQADgCAEgBQABgCAEgBQAGgBABgCIAKgDQAIgDABgCQADAAAGgDQAGgEACgCQAEAAAIgEQAHgEAEAAIAUgKIARgIQASgHACgCQAEAAAHgFQAHgFAFAAQAEAAAFgFQAGgFACAAQADAAAFgFQAGgFACAAQAGAAAJgHIAEgEIAEgDQAAgBAFgCQAFgBABgCQgGAAAEgBIAHgCQAAgDAHgBQAGgBADABQAAgCACgEQADgEgBgEIAOAAQAAgDADgCIAGgEIALgHQAAgEAKgFQAJgEAAgDIAMgDQAFgDACgIQAFgBANgWQAIgEAHgJIABgEQABAAAAgBQAAAAABAAQAAAAAAgBQABAAAAAAQADAAAEgHQAEgIAEAAQADgFAAgHQAEgCgBgEQABAAABgKQACgKACAAIgFgKQAAAGgJAAIgGAJQAAADgGAFQgGAEAAACIgFAFIgEAGQgCAAgFAEIgHAFIgDACQgEACAAADIgHADIgGADIADAAIgBADQAAAAAAAAQAAAAAAABQgBAAAAABQgBABgBAAIgFAFQgCACgGABQgGAAgCACQAEAAgEAFQgEAGgDAAQgJAKgKABQgDAHgMAFIgCABIgCADIgIABQgCABAAAFIgMADQgKACAAAEQgMAJAAABIgIACQgEACgEAAQAAAEgLACQgDgFgDAFIgFAHQAAACgIAFIgKAFQgEABgGAEQgIAFABADQAAACgLADIgMACQAAAEgIABQgHABABADQAAABgVAEQAAAGgMAFQgJADgJABQAAgEgLAGIgLAGQgDAAgHADQgHADAAABQgDAAgGACIgJACQAAACgHADQgHADgCgBIgBAFIgDABIgCADQgBAAgBAAQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAgBAAQAAAAAAAAQgBAAAAAAIgGAEIgCAAIgCgBQAAABgBAAQAAAAAAABQgBAAgBAAQAAABgBAAIgFABQgDACgCAAQgBAAAAAAQgBAAAAAAQgBAAgBABQAAAAgBAAQgCADgKAAQAAACgHACQAAACgIACIgLACIgNAFQAAABgHABIgTAJQgVAGgEACQAAACgIABIgLgBQgBACgEACQgDABgBADQgFACgDAAIAAAEIgMAAQAAAEgFACQgFABAAgCQgDAAgJAEQgIAEgEgBQAAAAAAAAQAAAAgBAAQgBAAAAAAQgBABgBAAIgGABQgCADgHAAIgKgBQgCAEgJAAIgWAHQAAABgLAEQgFACgIAAQgBgBAAAAQgBAAAAAAQgBgBAAABQgBAAAAAAIgFADIgIgCQAAAGgLABIgPAAIgHACQgEABgBACIgKAAQgWAIgDAAQgEAAgNACQgOACAAACIgYAEIgFABIgFACQgGAAgOADQgRADgCADQABgCAQAAQAAADAUAAQADgDAJABIANACQAAgDALABIALABIAFACgAmcGIQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAAAIAKAIQAHAGAEAAIACgDQABAAAAgBQAAAAAAgBQAAAAgBgBQAAAAgBgBQgCgDgEgDIgIgEIgDgBIgCABgAAQFjQACADACAAIAGABQAFABABgDIACgBQAAgBABAAQAAAAAAAAQABAAAAgBQAAAAABAAQAAgBAGgBQAFgBAAgBQAcgBAAgEQAIAEAAgEQAEgBAKADIAIgDQAEgCADAEQACACAEgBQAEAAACgDQABgBAEABIAHACIgDgDIACgFIAIgCIADADQAAABABAAQAAAAABAAQAAAAAAAAQAAgBAAgBQALABAEgBQAEgBAFgFIALAAQAHAAACgDQAFgDAOABQABgEAJABIAMABQAAgDAFABIAHACQAAACAJgGQAIgBAMABQAAgHAMAAQAAgBARgDQARgEADAAQAAAEAKgBQAKAAACgDIACgEQACgDADADQACACADAAIAFgBQAAgGABgBQACgCAGABQABADAGgCIAJgDQADAAAIADIAHgDQAAgFAKgCIAOgCQAHgDADgEQADgDAOADIgBgEQAAAAABAAQABAAAAAAQABgBAAAAQABAAAAgBQACgCACgBQACgBADACIAGABQAAgCAMgBIAPgBQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIACAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAABAAAAQAIAAAGgEIALgHQATAAACgEQALAAABgCQAFAAgDgFIAIgBIADgFQABgBAAAAQABgBAAAAQABAAAAAAQAAAAAAAAQACABADgCQABAAAAgBQABAAAAAAQABAAAAAAQABAAABAAQAAACAGAAQAGAAAAgCQAFAAAEgCIAHgHIAJgBQACgDADABIAGABQAAgBAPgFIARgGQgBAAgBgBQAAAAAAgBQAAgBAAAAQAAgBAAAAQABgCAFAAQACADAFgCIAGgCQAAgBAFgBQAGAAAAgDIAFABQACgBABAAQABgBAAAAQAAgBAAAAQAAAAAAAAQgBgDAMgEQANgDAAgCQAIAAAPgIQABgCAGABQAGABAAgDIADgDQAAAAAAgBQABAAAAAAQABAAABgBQAAAAABAAQAEABAFgDQAAgBAIgCIALgBQgBgEAFgDQAFgDABgDQAMABAAgDIAGABQAEABABgDIAIgHQAAgDAGgDQAGgEADAAIAJAAQAAABAQgKQAAgCAGgDIAGgFQAFAAAHgGQAGgGAEAAQAAACAPgKQAGgGAIAAQARgKAAgBIASgNQAJAAAKgGQACgGAEAAQACgCAIgDQAHgDABgDQAFAAACgFQADgFACgBQAKgFgCAAQABgDADgDIAGgFIAKgEQAAgEALgFQAJgGAAgCQARgVACgBIAGgMQAEgIgFgCQAAgCgHgDQgGgDAAgCQgBgCgDgDIgFgDIgIgGQgFgFgCgBQgYgKAAgEQgFAAgHgEIgMgGIgPgKIgKgFQgGgEgEAAQAAgBgGgCIgIgBQgRgGgCgDIgNgGIgIABQgHABgDgBIgEgCIgFgBQgOgJgCAAQAAABgPgGIgIgDQgCgDgOgCIgpgJQgFgFgSABQgPACgCgDQgDgEgFAAIgMABQgNACAAgDIgPAAQAAgDgFgBQgFgGgHADIgLAEQgGAAgWgIQAAAEgSAAQgTgBABgHQAAgEgEgBQgDgBgEABQgBADgHgCQgBAAgBAAQgBAAAAAAQgBAAAAAAQAAAAAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQAAAAgBAAQAAADgHgBQACAFAAAEQAGAAACAZQABAXgBAGQgBAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAABQgBAAAAAAQAAABAAAAQAAAAgBAAQABAAAAABQAAAAAAAAQAAABAAAAQAAAAAAAAIgBAQQgBAQgDAAQAAABAAABQAAAAAAABQAAAAABABQAAAAABABIgHANIgFAKQgEAHAAAFIgFAMQgEAMgGAAQACAFgFAAIABADQgCAAgCAFQgBAFgCAAQABAEgDADIgEADIgBAFQgDABAAADQgBAAgFAHQgFAHgFABQgBADgGACQgHACAAAEIgBAEIgBADQAAABgEAEIgFAEQAEAHgPADQgBAEgFAEQgHAEgCADQgEAHgPAHIgEAEIgFAEQgIAAgNALQgRAOgEACIgLAEQgHADAAAEIgJAGQgFAEgEABQAAgBgFAEQgEAEABAAIgRAIIgJAEQgJACAAADQgHAAgPAKQgOALgKAAQgCgBgGADIgIAEIgHAGQgEAEgEAAQgZAJgDAAQAAACgHAEQgIAEAAgDQgDgBgGADQgFADgDADQgMABgFAFQgEAAgHAFQgIAFgDAAQgDAEgRAAQgCADgCABIgEADIgGABQAAAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAIgFgDQgGgBgFADIgIAGQgBAFgKADIgKAEQgGADgDAAQAAABgSAFIgXAFQAAACgVAGQgVAHgCACQgSADgZAJQgGADgLAAQAAAEgNABIgQAHQAAgGgcAJQgDAAgFACIgIADIgKACIgMAEQgGAFgLACIgSAEIAEAAQABAAAAAAQAAAAAAAAQAAAAAAAAQAAABAAAAIAOACQALABABgCQAWAAAQADQAkgBAAAEQADABAUgDQAUgCAAgBQAGgDAGAEIAKAFQAAgBANgCIARgBIANgBQACABACADgApvE9IgNADQgFAHAQACQASADAAABIAQAAQAPABAAABIAOAAQgGgKABgBQAAAAABAAQAAAAAAgBQAAAAAAAAQgBgBAAAAIgCgBQgdAEAAgDQgIgDgGAAQAAgCgFAAIgGAAgAotFMIADABIACgBQAAAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAAAIgFAAIgCgBIAAAAgAnIFFIADADQACADABABIAGgBQABAAABAAQABAAAAAAQABgBAAAAQAAgBAAgBQAAgCgDgDQgDgEgFAAIgCAAQgDACAAAEgAlKErQAEAIADADIADAEQAIAAAEACIACgBIAMgCQAHgBADAAIA2gJQAAgBASgDIAUgDQA/gPAGAAQAlgKAEAAQAAgCASgDQASgDABgDQAHAAAIgDIANgEQAGAAAJgDIAMgEQACgDAYgFQAVgFAAgGQATAAAAgDIAWgGQAAgCAHgBQAHgCABgBIAEgBQABgBAAAAQABAAAAgBQAAAAABAAQAAgBAAAAQACgBAHABQAAgDAMgEQAMgEAEABQABgDAJgCQAHgCAAgCIAKgDQAIgDABgCQAFAAAJgDQAIgDAEgEQAFgEAMgCIAMgFQAKgEAAgBQAGgCAFgDIALgGQAVgHACgEIAJgDQAHgEAAgBQADAAAHgDIAJgGQAIAAALgIQAMgJAGgBQACgCARgJQAQgHgBgCIAKgHQALgFAAgBIAGgFQADgCAEgBQAIABAEgFIACgGQADgGAFAAIAEgEQAFgDAAgCQAEgBAHgFQAHgGAEgBQACAAACgEQABgEACgBIAEgCIADgCIAJgIQAEgCAEgGQAEgFADgCQAAgDALgLIAMgOIAFgJQAFgHACAAQABgFAEgGIAFgJQABAAACgFIACgFQADgIgBgFQgEAAgHAMQgJANgDACQAAAEgKAIIgIAIQgFAFgEACQAAAEgGAFIgHAHQgBACgHAEQgGAEAAADIgFAEQgDADgDABIgEAEQgDACgCAAIgGADIgGADQAAABgDADQgEADgBACIgIAFQgGAEgBACQgDAAgHAFIgJAIQgIACgNALQgNAKgJABQgEAFgKAEQgJADgGAAIgMALQgEAAgGAFQgFAFgDAAQgCACgGABQgGABgDADQgKADAAACQgCAAgDADIgEADQgBADgIAAQgIAAgCAEQgDACgDAAQgCADgGABIgLABQgJgBgGACQgCABgCAGQgDAFgDABQgDADgFgCQgFgCgCABQAAAEgFABQAAAEgoAQQgCAAgEACQgEADgCAAIgLADQgGAHgPAAQAAACgKACQgLADAAADIgLABQgHABgCADQgFAAgCABIgGAFIgVAEIgTAGQgBABgIACQgIABAAACIgWAGQgEAAgHADQgGACgFAAQgBACgLADQgLACAAABQgDAAgEADIgGACQgBABgFABQgEABgCgBQgNAFgDAAQgBADgLACIgKACQgPAGgHAAQAAACgLAAIgNgBQAAABgIACIgKACQgMAAgKAEQAAAEgJABIgJACIgTAAQgNAAgEAFIgDABIgCADQgKADgEAAQgBADgXAEQgXADAAACIgIAAgAuiD5QAAgDgNgCQAAAFANAAIAAAAgAwGDQIgCADIAMAJIAIACIAJABQADAFAXAJQAXAIAAgFQgMAAAAgFQgNgCAAgBIgQgJQgCAAgDgGQgEgHgFAAQAAgCgIAAIgIgBgAlVDQQgIADgBACIADAAQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAQAAACAkgFIAqgEQAAgCATgEIAWgEQABgCALAAIAOAAQAEAAAOgFQALgEAGACQAAgBAQgEIARgDQAAgDAKABQAJACAAgEIAJAAQAFAAACgDIAHgCQAEgFAOABQANABACgEQgHAAAFgDQAGgDADAAIAKgBIAIACIAGgCIAIgBQAAgBAAAAQAAAAgBAAQAAAAgBAAQgBAAgBAAIgFABQgCgFAWgGQATgFAIAAQAAgBAJgCQAJgBABgCIAGgBQACgBADABQAEADADAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAABAAQgCgEAEgBIAHgBIAIAEQAJAFACAAIgGgDIgDgIIAFgEQADgBAEACQABAAALgEQAJgEAAADQACABADgBQABAAABgBQAAAAABgBQAAAAAAgBQABAAAAgBQAKAAAEgEQAAgIAHAAQACgCATAAQADgBADgEQACgDADAAIARAAIADgHQADgDADABIAFACQgBgHAFABIAJACQADAAADgCQADgDACAAQACgCAIgEQAIgEACABQAAgFAQgCQAQgBAAgCIALgBIAEgDIAFgCQACgCAJgDQAJgCAAAEQAEABALgCQAFgEABgEQgDAAADgGIAEgGQADgCAAgIIALgFQAIgEAEAAQABABAIACIAKABQAAAEAKgFQAJgEABgDQgGAAAAgKQACAAAEgFIAHgHIAPgFQAPgDAYgMQAEgFAOgFQAMgFADgGQADgBALgLQAKgKAGAAQABgDAFgDIAFgFQABgCAHgFQAFgEAAgDQACAAAEgGQAEgGAAgCQADAAAIgTQAIgTgCgEQgBAAAAgKQABgKgDgBIABAAIgFgNIgDgHIgPAAQAAABgMgDQgNgDAAADQgfAGAAgCQgJACAAgCIgGABQgEABgDgDIgNABQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBAAgBAAIgEACQAAADgKABQgKABgDgCIgNAAIgCAEQgBAAAAAAQAAAAgBAAQAAgBAAAAQgBgBAAgBIgLAAQgBAGgLgDIgQgFQgCABgGACQgEABAAAFIgMgBIgLABQAAADgQABQgRABAAABIgUABIgHAAIgFADIgBABIgCABIgOABQAAABgFABIgGABQAAgBgPADQgQACAAACIgJACIgKACIgIAGQAAADgIgFQgCAAgCAGQgBADgDAAIgFABQAAAAgBABQAAAAAAAAQgBABgBAAQAAAAgBAAIgGABQAAABgBAAQAAABgBAAQAAAAgBABQAAAAgBAAQgEABgCACQgEADgDAAQAAgDgFAAIgIACQAAAEgTgCQAAAGgHACQgJACgCACIgFADIgFADIgFAAIgEgBQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAgBgBAAIgEgCIgHADIgHACQgCgDgEACIgFADIgEADQgDADAAACQgCAAAAAGIgDAEIgEABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBgBIgEgBQgEAHgRACIgQAJQgIAEgEgCIAAgEQAAAAAAAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgJAEQAAAHgCAAIgHgCQgBAAgGACQgGACgBACQgDAAgDACQgCADAAADIgKACQgKACgDAFQgEAAAAAEIgBAFIgOAHQgDAFgGAAIgKgCQABAKgEACQgJAEgBABQgKAHAAgEQgFgDgBACIAAADQABADgJAGQgJAFgDABQAAACgGADIgHADQAAgFgFADQgFAEACAAQAAAEgGAHQgFAGgFACQgCAHgMADQgHADgCgDQgDABgEAEQgEAFAFAAIgCAFQAAADgFAFIgFAFIgJAHQgFAFgBAEQgGAAgCACIgDAHQgDABgDAEIgFAHQACADgVATIgDADIAMgBIAjgEQAAAEAOgGIAGgBQAAAAABAAQAAgBAAAAQABAAAAABQAAAAABAAQAAAAAAABQAAAAABAAQAAAAAAAAQABAAAAAAQABgEAIgDIAIgDQAFAAARgDQAPgCADAGQABAAAAAAQAAAAABgBQAAAAAAAAQAAgBAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQABgBAAAAIAKAAQAAgBAGAAIAHAAQgBABABAAQAAAAAAABQAAAAABAAQABgBABAAQAAgFAPgCIATgCQAAgDAJAAIALgBQAAgFAVgCQAUgBAAACQADgBADgDQADgDABAAQAAgBAGACIAHABQAAAGARgKQAAgBAGgDIAHgCQAEAGAGgBIAOgCIALgBQAGAAAAgFQgDABgEAAQAAgCADgCQABAAABAAQAAgBABAAQAAgBAAAAQABgBAAAAIAMgCQAAAAABgBQAAAAABAAQABAAAAgBQABAAAAAAQAAgDAKgBIAMAAQAGAGAEgFQAHgIAEgBQAKAAAAgCQAFABACAEQABAEgGAAQAAADAGACQAFACAAgEQgBAAAAAAQgBAAgBgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQABAAAAgBQAAAAABAAQABgBABAAQAAgCAIAAIAEgCQAEgDAAgCQAGAAADgCQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAIAFAAQAEgGAJAAQACABAFgCIAHgEIAJgFQAIgDAAADQAJAAgDgBQgGgDgBgCQgGgBAFgBIAHgCIAFAFQABACAEAAQAKABAAgCIATgJQAEAAAIgDQAIgDAFgBQAAgDAJgDQAJgDAEAAQABgBAEgCIAGgDIAHgCQAFgCACABQAEABADgDQADgEADgBIAHgEQAGgCACADQACADgKALQgDAAgGAEQgGAEgEAAQAAAEgKAFQgMAFgBADQgCAEgIABQgHABgCADQgHAAgJAKIgXAIIgPANIgTAGQgUAEgGAIQgFgBgEADQgGADgDAAQAAABgKAAQgJABAAAFIgMACQgJACgEAEQgKAEgGABQAAABgHADIgIAEQgGAAAAgCIgIADQgCADgJADIABACQgHADgEAAQgJgBgFACQgRAKAAgCQgHAAgMAEQgMAEgIAAQAAABgSADQgSADAAADQgXAIAAgCQgDAAgHAEQgGAEgDAAIgNAEIgPAEIgUAEQgdAJAAgCQgWAAgCAEQgIADgFAAQAAgCgHACIgJADQgSAGgFAAQgIACgFAAIgPAAQgEAFgKgBIgPAAQAAABgPADIgBAAIgGACgAwSDKQADgGgHgBQAAgEgHgFQgCAAgHgEQgGgDgDAAQAAgDgGgFQgGgFgDAAQABgCgJgGQgKgGgDAAQACAEAFAGQAFAGAEACIAJAJQAEAEADAAQASAQAAgCIAGgBQAAAGAJAAgAn9CSQgEABgBADQgCACACADQAEACgCADIgEADIAQgEQACgBAKADIAEgBIACgDIACAAIAJgCIgDgUIgCgIQgBgEABgDQABgPACgHQADAAgBgGQgBgHgFAAIgKAOQAAAEgFAIQgFAHABADQgFACgCADQgBABgCAGQAAAAgBAAQAAAAgBABQAAAAAAABQgBAAAAABQgBADgCABQAAAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBgBIgDgBQgCABALAGgAmRBJQgEAAgDAIQgDAHgCABIgEARIABACQgDAAgCARQgDAQACACIAHgHQADgNADAAIAEgIQAEgHABAAIADgFIADgHQACAAAHgQIAGgFIAGgHQAFAAAAgJQAAAAAAAAQABAAAAAAQABgBAAAAQAAgBABgBQAAAAAAgBQABgBAAAAQABAAAAAAQABgBAAAAQAHgGABgEQAAAAABAAQAAAAAAgBQABAAAAAAQAAgBABAAIABgEQAGgDAGgKQADAAAFgIQAFgHAFAAQAYgJgLAAQAAgEAEgDIAHgCQAAgFAHgDQAGgEAAgDQAEgBADgEQADgEADAAQABgDAKgFQAJgEAAgDQAIgFAFAAQAAgEAHgDQAGgEAAgCIAFgEIAGgDQAEgCACgCQACAAAHgFQAGgGABABIAJgFQAHgDABgDQAGgEABgFIAJgBQAFgBAHgGQAAAGAKgHIAMgIQACAAAFgDIAFgFQACgBAGgCIAGgCQAcgJAAgCQAEAAAHgEQAGgCAFAAQACgDADABQAGABACgGQADAAACgCIAHgEQACgBAMgDQAKgCAAgCIAIgDQAEgCAAgDQAMAAABgDIAHgBQAGgBAAgCQAEAAAJgDQAJgEAEAAQAAgBAHgDIAJgCQAsgNAEAAQAAgBALgDIANgDQAAACAIgBQAIgBAAgEQAEAAAJgCQAIgDAFAAIAagGQAAgCAJgBIAMgBQAAgBAKgCQAKgBAAgBIAJgCQAFgCAEAAIAJAAQAGAAADgDIAbgEQAAgCASgCIAWgCQACgDALgBIAPgBQAQABAMgDQAAgEAugBIAzgBQAAAAAAAAQABgBAAAAQABAAABAAQABAAABAAQABAAABAAQAAAAABAAQAAgBAAAAQAAAAAAgBIADAAIgBgCQgDAAgEgGQgDgHgDAAQAAgCgGgGQgGgFAAgDQAGgCAIACQAIADAAAHQAEAAAEAEQAEADABADQADADAAADQAAABABAAQAAAAAAAAQAAAAABAAQAAAAABAAIACABIADACIAGAAQAFACAKgBIAQAAIA6ADQAHABAGgBQAAgBARABIATACQAkADAAABIApADQAkAEAAAFQAIAAARAEQARAEAIAAQAAACAMABQANACAAACIANAEQAIADAFAAIAJAEQAFACADAAQAAACAHABQAIAAABACQACAAAVAIQADAAAHADQAHADACACIAGADQAFACAAgCIAFADIAMAFQAJAFAAABQAEAAAHAEQAGAFAEAAQAAABAGADQAFAEACAAQAAABAHACQAGADABACQACADAIAEQAHADACAEQAGAAgFgIQgGgIgEAAIgDgDQgDgCAAgCQgHAAgGgJQgCAAgJgHQgJgIAAgCQgOAAAAgGIgDgCIgFAAQgFgGgDgCIgLgGQgGgDgGAAQgCgEgJgCQgDgBgBgCIgEgDQAAgCgOAAQAAgEgJgCIgNgCQgFAAgGgDQgHgCABgEQgHAAgLgIQgKgHgGAAQAAgCgIgBIgIgBQgVgFAAgCIgMgDIgKgCQAAgEgYgEQgVgEgHAAQAAgBgMgBQgNAAAAgDIgSgDQAAgCgWgCIgXgDIgegBQAAgCgJAAQgLgBgBgBIgWgBQAAADgggCQgBgCgLAAQgLAAAAABQgDABgEgBIgHgBQgOACgGgBIgJACQAAACgSgCQAAADgSABQgRACgEgCQAAADhWAEQgEAAgTADQgVADAAADQgSAAAAABIgRADQAAAFgpACQAAACgNACIgRADQgBADgHAAQgIAAgCADQgEgBgFACIgIABQAAACgLAAQgLABAAACIgZAIQgOAEgKAAIgyAPQAAADgKACQgMABgBADQgNAFgJABQAAABgFACIgGACQAAABgJADIgMACQgCAEgIACQgJADgCADQgEAAgFADIgIADQgRAEgEAFQgEAAgHAFQgHAFgEAAQgDADgFAEQgGADgDAAQgCACgMAHQgEAAgHAGQgGAFgGgBQgCADgHAAQAAACgHADQgKAEgGAFQgQALgJAEIgHAHQgEAEgEAAQABgCgIAGQAAADgIAHIgMAHQgIAJgJAEIgDAEIgFADQAAAAgBAAQAAAAgBAAQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAQgBAAgBAAIgDgBIgDABQgDADgKAFIgCAEIgDADQAAACgDAEQgEADgBAAIgFAGIgGAEQAAACgHAGQgCADgEABIgGADIgDAFQAAADgDABIgFADQgBABAAAEQAAAEgCABIgEADQgBAAAAAAQgBAAAAABQgBAAAAAAQAAABgBAAIgDAEIgDAHQgEAFgCAAQAAAFgIAFQgIAFAAAEQABAAgDAPIAAAGQAAAEgDABQAAABAAAAIgBAAgAuelOQgBAAAAABQgBAAAAAAQgBABAAAAQgBAAAAABIgCAEQgFAAgBACQgDAAgEADQgFACgBACQgIAFgDAAQgGAGgPAEQgBAEgIABQgJABAAADIgGAFQgFAEAAABQgLAAgBAFIgPAMQgEAAgLAIQgIAFgEAGQgCACgEADQgEACgCADQAAAFgHADQgIAEgBAEQgCABgBAEQgCAEgDABQAAACgFADQgFAEAAADIgHAHIgHAJIgCABQABACAegXQAggXAGgBIAGgEQADgCACAAIADgDIADgDQgBAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBIAJgBQAHgBABgCIADgCIACgCIAGgEQAEgDACAAQACgDAIgDQAIgEABgDQADAAAEgDQAEgDACgDQAIgCACgCQADAAAGgDIAKgEQACgCAFAAQADABABgFQAAgHALAAIAGgHQABgCAFABQAEABABgDIAHgDIAIgFQAAgCANgFQAOgGACABIAAgEIAKgEQAGgDADgBIAKgEQAGgDABgCIAHgCIAGgCQACgCADAAIAHAAQABgDADgCQAFgGAMgCIAUgDQABgCAHgDQAHgCADAAQAAgEAGADQAEABAGgFIAGgDIAHgCQAEgGAcgGIAPgDQALgDAAgDIAFgBIAFgCIAHAAQAEAAAAgEQAAAAgBgBQAAAAAAgBQAAAAAAAAQAAgBAAAAIACgDIgFgCIgmAJIgCAAQAAABgJACQgIABAAABQgGAAgJAFQgKAFgEAAIAAgCQgEAAgIADQgHACgFAAQgEgBgBACIgEAEQgDADgCAAIgFgCIgHADQgHADAAADIACAAQgBADgEAAQgDABABgEIgIADQgGACgDAAIgJAGIgDAEQgCABgDgBQgCAFgLAEQAAABAAAAQAAAAgBAAQAAABgBAAQgBAAgBAAQgBAAgBAAQgBAAAAAAQgBAAAAAAQAAABAAAAIgJABQgEABgBAGIgDABQgBAAAAAAQgBAAAAAAQAAAAAAAAQAAAAAAgBQgIAAAAgCQgBAAAAABQgBAAAAAAQgBAAgBABQAAAAgBAAQgDADgCAAIgLAGQgKAGABABIgLAFIgKgBIgDAAgAkVkOQgEgCAIgFIAJgGIAEgBIADgCQAAAAABgBQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQABAAAAABQAAAAAAAAQAAAAABAAQgPAOgHAAIgDgBg");
	this.shape_1.setTransform(-246.3661,64.3125);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AiJCHQg2g5ABhRQAAhWA3g1QA3g1BXAAQBXAAAvAzQAzA2AABmIkqAAQATBwB6AAQBHAABOgtIAABIQgoAYglAKQgoALg0AAQheAAg6g9gAhDhqQgdAXgIAuIDUAAQgBgsgbgZQgagYgtAAQgvAAgdAYg");
	this.shape_2.setTransform(269.85,97.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AiPD9Qg3ggAAgyQAAgqAagZQAagZA3gMQgqgXAAgZQAAgSASgOQASgOAegHIAAgCQgugRgZgfQgWgcAAgqQAAg9AygiQAygjBUAAICvAAIAAA6IhXAAQAZAWAJATQALARgBAYQAAAXgMAZQgMAXgPAOQgcAbhPAMQhAAKAAAWQAAAOAgAMQAcAKBEAMQB7AVAABUQAAA5g1AfQg1AgheAAQhVAAg3gggAhbB/QgbAPAAAZQAAAdAeAPQAeAPA6AAQA2AAAfgPQAfgOAAgaQAAgggygQQgmgMgyAAQgqgBgbARgAg8jIQgZAUAAAdQABAfAXASQAXAUAmgBQAjAAAXgUQAXgTAAgfQAAgbgZgUQgYgTgggBQgjABgZATg");
	this.shape_3.setTransform(229.4,106.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AA6C7QgQgKgFgTQg3Amg7AAQgtAAgfgcQgcgbAAglQAAgyAvgeQAagQBHgWIBLgYIAAgUQAAgigTgRQgTgQgmAAQhLABg8A9IAAhRQAygzBcAAQBDAAApAeQAtAhAAA9IAADBQAAAUAQAAQAOgBAegTIAAAtQgeARgPAGQgRAGgTAAQgcAAgPgJgAg4AmQgoAXAAAdQAAAXARAQQARAOAaAAQAlAAAlgfIAAhuQhDAVgbAPg");
	this.shape_4.setTransform(191.3,97.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgvDGQgjggAAg1IAAjGIhKAAIAAgIICdiJIAABOICGAAIAABDIiGAAIAADAQAAAeAVAPQAQAMAYAAQArAAA0gcIAABGQgWALgdAHQgfAHgUAAQhCAAgkghg");
	this.shape_5.setTransform(152.55,93.525);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABeDAIAAjoQAAgqgWgZQgXgZgmAAQgaAAgZANQgYAMgeAeIAAENIhUAAIAAl4IBUAAIAAAyIACAAQAYgbAigPQAhgPAjAAQBAAAAmAlQArAoAABLIAADng");
	this.shape_6.setTransform(116.275,96.675);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AA6C7QgQgKgFgTQg3Amg7AAQgtAAgfgcQgcgbAAglQAAgyAvgeQAagQBHgWIBLgYIAAgUQgBgigTgRQgSgQgnAAQhKABg8A9IAAhRQAygzBcAAQBDAAApAeQAsAhABA9IAADBQAAAUAQAAQAOgBAegTIAAAtQgeARgPAGQgRAGgTAAQgcAAgPgJgAg4AmQgoAXAAAdQAAAXARAQQARAOAaAAQAlAAAlgfIAAhuQhCAVgcAPg");
	this.shape_7.setTransform(75.2,97.05);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgLDAIjAl/IBcAAIBxDmIBwjmIBaAAIi7F/g");
	this.shape_8.setTransform(33.775,97.425);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAOD5QheAAg4g2Qg3g1AAhbQgBhRA8g0QA7g1BcAAQArAAAuAPIAAiAIBUAAIAAHxgAhEggQgmAjAAA7QAAB8CCAAIBUAAIAAjvQgpgPglAAQg8AAgmAkg");
	this.shape_9.setTransform(-9.45,91.025);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AC6DyIhJiOIjlAAIhECOIhQAAIDpnjIA2AAIDyHjgAhWAmICnAAIhWitg");
	this.shape_10.setTransform(-54.775,91.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("ABdDAIAAjoQABgqgXgYQgWgZgmgBQgaAAgYANQgZAMgcAeIAAENIhUAAIAAl4IBUAAIAAAyIABAAQAYgbAhgQQAigPAiAAQA/AAAmAmQAqApAABJIAADog");
	this.shape_11.setTransform(331.75,28.15);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AihCMQg/g5AAhWQAAhRBAg4QBAg3BeAAQBiAABBA2QBAA3AABTQAABZg/A3Qg/A3hlAAQhgAAg/g4gAhkhcQgnAjAAA2QAAA7AmAlQAlAkA9AAQBCAAAmgjQAngkgBg8QAAg3gogjQgogkg+AAQg7AAgmAkg");
	this.shape_12.setTransform(285.3,28.525);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AiOD9Qg2ggAAgyQAAgqAZgZQAagZA3gMQgrgXAAgZQAAgSATgOQASgPAegGIAAgCQgugSgYgeQgXgcAAgqQAAg9AygiQAxgjBUAAICtAAIAAA5IhWAAQAYAXAKASQAKASAAAYQAAAWgMAaQgMAXgPAOQgcAbhPAMQg/AKAAAWQAAAOAhAMQAbAKBDAMQB6AVAABUQAAA4g0AhQg1AfhcAAQhVAAg3gggAhbB+QgbARAAAYQAAAdAfAPQAeAOA5AAQA2AAAegOQAfgOAAgaQAAgggygQQglgMgyAAQgqAAgbAPgAg7jIQgZAVAAAbQAAAgAXASQAXATAmAAQAjAAAWgTQAXgVAAgeQAAgbgYgUQgYgUggABQgjAAgYATg");
	this.shape_13.setTransform(241.575,38.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AiICHQg1g5AAhSQAAhVA3g1QA3g1BWAAQBWAAAvAzQAyA2AABlIknAAQATByB5AAQBGAABNgtIAABIQgnAXglAKQgoALg0AAQhdAAg5g9gAhChqQgdAYgJAtIDTAAQgCgrgagZQgagZgsAAQguAAgdAYg");
	this.shape_14.setTransform(199.925,28.525);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AiZDAIAAl4IBUAAIAABXIACAAQA8hfA8AAQAxAAA0AsIgsBBQgTgQgXgLQgVgKgPAAQgqAAgdAiQgeAhAAAxIAADEg");
	this.shape_15.setTransform(166.55,28.15);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AjMCnQhLhEAAhjQAAhjBMhEQBQhIB7AAQB9AABPBIQBMBEAABjQAABjhLBEQhQBJh+AAQh8AAhPhJgAiQh/Qg6AzAABMQAABNA6AzQA5AzBXgBQBXABA6gzQA6gzAAhNQAAhMg6gzQg6gyhXAAQhXAAg5Ayg");
	this.shape_16.setTransform(116.7,24);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AiICHQg1g5AAhSQAAhVA3g1QA3g1BWAAQBWAAAvAzQAyA2AABlIknAAQATByB5AAQBGAABNgtIAABIQgnAXglAKQgnALg1AAQhdAAg5g9gAhChqQgdAYgJAtIDTAAQgCgrgagZQgagZgsAAQguAAgdAYg");
	this.shape_17.setTransform(62.775,28.525);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AiZDAIAAl4IBUAAIAABXIACAAQA8hfA8AAQAxAAAzAsIgsBBQgSgQgWgLQgWgKgPAAQgqAAgdAiQgeAhAAAxIAADEg");
	this.shape_18.setTransform(30,28.15);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AA5C7QgQgJgFgUQg1Amg7AAQgtAAgegcQgcgaAAgmQAAgyAugeQAagRBHgVIBJgYIAAgUQAAgjgTgQQgSgQgmAAQhLAAg6A/IAAhSQAxgzBbAAQBCAAApAeQAsAhAAA9IAADBQAAAUAQAAQAPAAAdgUIAAAtQgdARgQAGQgQAGgTAAQgcAAgPgJgAg3AmQgoAWAAAeQAAAYARAPQARAOAaAAQAkAAAkgfIAAhuQhCAVgaAPg");
	this.shape_19.setTransform(-9.325,28.525);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AinCgQhDhDAAhWQAAhqBRhGQBRhGB7AAQBLAABoAmIAABIQhegwhWAAQhZAAg6AzQg8AzAABMQAABPA7AxQA6AxBdAAQBcAABag0IAABJQgqAUgpAKQgxALg4AAQiGAAhQhQg");
	this.shape_20.setTransform(-56.9,24.45);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-367.1,0,734.3,135.2);


(lib.BKGDrubine = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E40571").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BKGDrubine, new cjs.Rectangle(-150,-125,300,250), null);


(lib.LOGO = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.coahreveps("synched",0);
	this.instance.setTransform(116.45,35.7,0.28,0.28,0,0,0,415.9,115.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.LOGO, new cjs.Rectangle(-102.7,3.3,205.60000000000002,37.800000000000004), null);


(lib.EndScreen = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Find out
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E41C70").s().p("AgNAOQgFgGAAgIQAAgHAFgGQAGgFAHAAQAIAAAGAFQAFAGAAAHQAAAIgFAGQgGAFgIAAQgHAAgGgFg");
	this.shape.setTransform(-190.075,84.925);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E41C70").s().p("AgxBPIAEgbQAFACAEAAQANABAEgJIAEgKIgvh1IAhAAIAdBRIAehRIAhAAIg3CGQgGAQgKAHQgKAFgRAAQgJAAgFgCg");
	this.shape_1.setTransform(-199.3,83.15);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E41C70").s().p("AgYBRIAAhYIgTAAIAAgbIATAAIAAgEQAAgUALgLQALgLAQAAQAVAAAJALIgLASQgFgEgIAAQgOAAAAARIAAAEIAXAAIAAAbIgXAAIAABYg");
	this.shape_2.setTransform(-208.55,78.475);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#E41C70").s().p("AgOBSIAAhzIAdAAIAABzgAgMgyQgFgGAAgHQAAgIAFgFQAGgFAGAAQAIAAAFAFQAFAFAAAIQAAAHgFAGQgFAFgIAAQgGAAgGgFg");
	this.shape_3.setTransform(-216.275,78.375);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#E41C70").s().p("AgOBQIAAifIAdAAIAACfg");
	this.shape_4.setTransform(-222.325,78.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E41C70").s().p("AgoAzQgNgLAAgRQAAgUANgIQALgJAQAAQAYAAAMAOIAAgOQAAgKgHgFQgHgFgKAAQgTAAgPAOIgMgVQAUgTAeAAQAWAAANAKQAQALAAAXIAABKIgfAAIAAgMQgNAPgXAAQgPAAgMgKgAgQAKQgGAFAAAIQAAAIAGAEQAGAFAJAAQAQAAAIgKIAAgOQgIgKgQAAQgJAAgGAEg");
	this.shape_5.setTransform(-232.175,80.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#E41C70").s().p("Ag2AXIAAhSIAfAAIAABGQAAAVAVAAQAPAAALgNIAAhOIAfAAIAABzIgfAAIAAgOQgQARgYABQgmAAAAglg");
	this.shape_6.setTransform(-245.25,80.95);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E41C70").s().p("AAcBRIAAg6QgOASgVAAQgWAAgOgQQgPgRAAgbQAAgdAPgQQAOgQAWgBQAVABAOASIAAgQIAfAAIAACfgAgSgsQgIAJAAAQQAAAOAIAJQAIAJAMAAQAHAAAIgEQAHgDAEgGIAAgoQgEgGgHgEQgIgDgHAAQgMAAgIAJg");
	this.shape_7.setTransform(-259.525,82.85);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#E41C70").s().p("Ag2AXIAAhSIAfAAIAABGQAAAVAVAAQAQAAAKgNIAAhOIAeAAIAABzIgeAAIAAgOQgQARgYABQgmAAAAglg");
	this.shape_8.setTransform(-279.2,80.95);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#E41C70").s().p("AgsArQgQgSAAgZQAAgZAQgRQARgSAbAAQAcAAARASQAQARAAAZQAAAZgQASQgRASgcAAQgbAAgRgSgAgVgWQgHAJgBANQABAOAHAKQAIAKANAAQAOAAAIgKQAIgKAAgOQAAgOgIgIQgIgKgOAAQgNAAgIAKg");
	this.shape_9.setTransform(-293.05,80.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#E41C70").s().p("AgxBPIAEgbQAEACAFAAQANABAEgJIAEgKIgvh1IAgAAIAeBRIAfhRIAgAAIg3CGQgFAQgLAHQgKAFgRAAQgIAAgGgCg");
	this.shape_10.setTransform(-306.1,83.15);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#E41C70").s().p("AgYBRIAAhYIgTAAIAAgbIATAAIAAgEQAAgUALgLQALgLAQAAQAVAAAJALIgLASQgFgEgIAAQgOAAAAARIAAAEIAXAAIAAAbIgXAAIAABYg");
	this.shape_11.setTransform(-201,54.475);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#E41C70").s().p("AgOBSIAAhzIAdAAIAABzgAgMgyQgFgGAAgHQAAgIAFgFQAGgFAGAAQAIAAAFAFQAFAFAAAIQAAAHgFAGQgFAFgIAAQgGAAgGgFg");
	this.shape_12.setTransform(-208.725,54.375);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#E41C70").s().p("AgSArIAAg7IgUAAIAAgbIAUAAIAAgfIAdAAIAAAfIAYAAIAAAbIgYAAIAAAzQAAANALAAQAHAAADgEIAHAYQgJAHgRAAQgfAAAAggg");
	this.shape_13.setTransform(-221.925,55.375);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#E41C70").s().p("Ag1AXIAAhRIAeAAIAABFQAAAVAVAAQAQAAAKgNIAAhNIAfAAIAABzIgfAAIAAgPQgQASgYAAQglAAAAglg");
	this.shape_14.setTransform(-232.9,56.95);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#E41C70").s().p("AgsArQgRgRAAgaQAAgYARgSQARgSAbAAQAcAAARASQARASAAAYQAAAagRARQgRASgcAAQgbAAgRgSgAgVgWQgIAJABANQgBAPAIAIQAIAKANAAQANAAAJgKQAHgIAAgPQAAgNgHgJQgJgLgNABQgNgBgIALg");
	this.shape_15.setTransform(-246.75,56.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#E41C70").s().p("AgrBBQgPgQAAgdQAAgbAPgQQAOgRAXAAQAVAAAOASIAAg6IAeAAIAACfIgeAAIAAgPQgPARgUABQgXgBgOgQgAgSgDQgJAJABAOQgBAQAJAJQAIAJAMAAQAHAAAIgEQAHgDAFgGIAAgpQgFgFgHgDQgIgEgHAAQgMAAgIAJg");
	this.shape_16.setTransform(-267.2,54.75);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#E41C70").s().p("AAYA8IAAhFQAAgWgWAAQgOAAgLANIAABOIgfAAIAAhzIAfAAIAAAOQAPgSAZAAQAmABgBAkIAABSg");
	this.shape_17.setTransform(-280.75,56.65);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#E41C70").s().p("AgOBSIAAhzIAdAAIAABzgAgMgyQgFgGAAgHQAAgIAFgFQAGgFAGAAQAIAAAFAFQAFAFAAAIQAAAHgFAGQgFAFgIAAQgGAAgGgFg");
	this.shape_18.setTransform(-290.725,54.375);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#E41C70").s().p("Ag3BQIAAifIBvAAIAAAeIhOAAIAAAhIBNAAIAAAeIhNAAIAABCg");
	this.shape_19.setTransform(-300.2,54.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// tty
	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#335192").s().p("AADAoIAAg5IgMAOIgKgLIAYgZIAPAAIAABPg");
	this.shape_20.setTransform(33.025,43.625);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#335192").s().p("AADAoIAAg5IgMAOIgKgLIAYgZIAPAAIAABPg");
	this.shape_21.setTransform(28.125,43.625);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#335192").s().p("AgRAoIAbhAIgnAAIAAgPIA7AAIAAAMIgeBDg");
	this.shape_22.setTransform(22.825,43.625);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#335192").s().p("AgIAoIAAghIgeguIAUAAIASAgIATggIAUAAIgfAuIAAAhg");
	this.shape_23.setTransform(12.65,43.625);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#335192").s().p("AgIAoIAAhAIgXAAIAAgPIA/AAIAAAPIgYAAIAABAg");
	this.shape_24.setTransform(5.375,43.625);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#335192").s().p("AgIAoIAAhAIgXAAIAAgPIA/AAIAAAPIgYAAIAABAg");
	this.shape_25.setTransform(-1.525,43.625);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20}]}).wait(1));

	// phone no
	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#003C71").s().p("AggAjQgOgOAAgVQAAgTANgOQAOgOAUAAQAVAAAMANQANAOAAAWIAAAGIhEAAQACAJAGAFQAIAHAKgBQAPABAJgKIALARQgOAMgYAAQgUAAgOgNgAAXgIQAAgIgFgFQgGgGgLAAQgJAAgHAGQgFAFgBAIIAsAAIAAAAg");
	this.shape_26.setTransform(26.75,89.05);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#003C71").s().p("AgaAvIAAhbIAYAAIAAANQAMgPARAAIAAAYIgHgBQgGAAgHADQgHADgCAFIAAA7g");
	this.shape_27.setTransform(18.525,88.925);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#003C71").s().p("AgjAiQgNgOAAgUQAAgTANgOQAOgOAVAAQAWAAAOAOQANAOAAATQAAAUgNAOQgOAOgWAAQgVAAgOgOgAgQgSQgHAIAAAKQAAALAHAIQAGAHAKABQALgBAGgHQAHgIAAgLQAAgKgHgIQgGgHgLAAQgKAAgGAHg");
	this.shape_28.setTransform(9.175,89.05);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#003C71").s().p("AAtAvIAAg5QAAgOgOAAQgMAAgHAKIAAA9IgXAAIAAg5QAAgOgOAAQgLAAgIAKIAAA9IgYAAIAAhbIAYAAIAAAMQAEgFAHgEQAJgFAKAAQATAAAGARQAEgHAIgFQAJgFAKAAQAbAAAAAcIAABBg");
	this.shape_29.setTransform(-4.425,88.925);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#003C71").s().p("AATAvIAAg2QAAgRgRAAQgMAAgIAKIAAA9IgYAAIAAhbIAYAAIAAAMQAMgOATAAQAeAAAAAdIAABAg");
	this.shape_30.setTransform(-22.875,88.925);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#003C71").s().p("AgaAvIAAhbIAYAAIAAANQAMgPARAAIAAAYIgHgBQgGAAgHADQgHADgCAFIAAA7g");
	this.shape_31.setTransform(-31.375,88.925);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#003C71").s().p("AggApQgKgJAAgOQAAgPAKgHQAKgHAMAAQATAAAJALIAAgLQAAgHgFgFQgGgEgIAAQgOAAgMALIgKgRQAQgOAXAAQASgBAKAIQANAJAAASIAAA7IgZAAIAAgKQgJAMgTAAQgMABgKgIgAgNAIQgEAEAAAGQAAAHAEADQAGAEAHAAQAMAAAGgIIAAgMQgGgIgMAAQgHAAgGAEg");
	this.shape_32.setTransform(-40.65,89.05);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#003C71").s().p("AggAjQgOgOAAgVQAAgTAOgOQANgOAUAAQAVAAAMANQANAOAAAWIAAAGIhEAAQACAJAGAFQAIAHAKgBQAPABAKgKIAKARQgOAMgYAAQgUAAgOgNgAAXgIQAAgIgFgFQgGgGgLAAQgKAAgGAGQgFAFgBAIIAsAAIAAAAg");
	this.shape_33.setTransform(-50.75,89.05);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#003C71").s().p("AgLBAIAAh/IAXAAIAAB/g");
	this.shape_34.setTransform(-58.45,87.3);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#003C71").s().p("AgjAiQgNgOAAgUQAAgTANgOQAOgOAVAAQAWAAAOAOQANAOAAATQAAAUgNAOQgOAOgWAAQgVAAgOgOgAgQgSQgHAIAAAKQAAALAHAIQAGAHAKABQALgBAGgHQAHgIAAgLQAAgKgHgIQgGgHgLAAQgKAAgGAHg");
	this.shape_35.setTransform(-71.225,89.05);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#003C71").s().p("AgOAiIAAgvIgQAAIAAgVIAQAAIAAgZIAXAAIAAAZIATAAIAAAVIgTAAIAAApQAAAKAIAAQAGAAADgDIAFATQgHAGgNAAQgZAAAAgag");
	this.shape_36.setTransform(-79.925,87.925);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#003C71").s().p("AAOBAIgXgkIgLAMIAAAYIgYAAIAAh/IAYAAIAABMIAigpIAeAAIgkApIAlAzg");
	this.shape_37.setTransform(-92.5,87.3);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#003C71").s().p("AgbAjQgOgOgBgVQABgUAOgOQANgNAUAAQAZAAALAQIgPAPQgHgKgMABQgLgBgGAIQgIAHABALQgBAMAIAHQAGAIALAAQAMAAAHgKIAPAOQgLASgZgBQgUAAgNgNg");
	this.shape_38.setTransform(-102.85,89.05);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#003C71").s().p("AgLBBIAAhbIAXAAIAABbgAgJgoQgFgEABgGQgBgGAFgEQAEgEAFAAQAGAAAEAEQAEAEABAGQgBAGgEAEQgEAEgGAAQgFAAgEgEg");
	this.shape_39.setTransform(-110.1,87.125);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#003C71").s().p("AgLBAIAAh/IAXAAIAAB/g");
	this.shape_40.setTransform(-114.9,87.3);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#003C71").s().p("AgcAjQgOgOABgVQgBgUAOgOQAOgNAUAAQAYAAAMAQIgPAPQgHgKgNABQgJgBgIAIQgGAHAAALQAAAMAGAHQAIAIAJAAQANAAAHgKIAPAOQgMASgYgBQgUAAgOgNg");
	this.shape_41.setTransform(-121.95,89.05);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#003C71").s().p("AgaAvIAAhbIAYAAIAAANQAMgPARAAIAAAYIgHgBQgGAAgHADQgHADgCAFIAAA7g");
	this.shape_42.setTransform(-134.625,88.925);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#003C71").s().p("AgjAiQgNgOAAgUQAAgTANgOQAOgOAVAAQAWAAAOAOQANAOAAATQAAAUgNAOQgOAOgWAAQgVAAgOgOgAgQgSQgHAIAAAKQAAALAHAIQAGAHAKABQALgBAGgHQAHgIAAgLQAAgKgHgIQgGgHgLAAQgKAAgGAHg");
	this.shape_43.setTransform(-143.975,89.05);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#E41C70").s().p("AgrBfIBEiaIhgAAIAAgjICOAAIAAAcIhHChg");
	this.shape_44.setTransform(28.15,63.125);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#E41C70").s().p("Ag5BGQgUgbAAgrQAAgrAXgbQAZgcAoAAQAiABAXATIgTAgQgQgPgWgBQgUABgOAQQgNAPAAAWIAAAFQAIgLAMgGQAOgIAOAAQAcAAASAQQATAQABAdQAAAcgVASQgUATggAAQgoAAgWgcgAgkAYQACAQAIAKQALAMARAAQAPABAKgKQAJgIAAgLQAAgOgKgHQgKgHgPAAQgWAAgPASg");
	this.shape_45.setTransform(11.75,63.15);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#E41C70").s().p("Ag7BEQgTgbAAgpQAAgnATgbQAVggAmAAQAmAAAWAgQATAbAAAnQAAApgTAbQgWAegmAAQgmAAgVgegAglAAQAAA+AlAAQAlAAAAg+QAAg+glAAQglAAAAA+g");
	this.shape_46.setTransform(-5.825,63.15);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#E41C70").s().p("Ag7BEQgTgbAAgpQAAgnATgbQAVggAmAAQAmAAAWAgQATAbAAAnQAAApgTAbQgWAegmAAQgmAAgVgegAglAAQAAA+AlAAQAlAAAAg+QAAg+glAAQglAAAAA+g");
	this.shape_47.setTransform(-23.525,63.15);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#E41C70").s().p("AghAQIAAgfIBDAAIAAAfg");
	this.shape_48.setTransform(-36.725,65.75);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#E41C70").s().p("AhEBhIAAggQA9guARgRQAWgUgBgRQAAgMgJgHQgIgGgNAAQgeAAgVAWIgXgbQAbgfAuAAQAfAAAUAQQAWARAAAcQgBAYgTAWQgRAVgnAdIBNAAIAAAkg");
	this.shape_49.setTransform(-49.85,62.975);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#E41C70").s().p("AhKBEIAXgcQAUAVAeAAQAQAAAKgIQAJgJAAgMQAAgMgJgIQgJgIgQAAQgXAAgQAQIgdgIIAAhsICCAAIAAAjIhZAAIAAAvQAQgQAZAAQAZAAARAQQATARAAAcQAAAegVASQgVASghAAQgvAAgbgdg");
	this.shape_50.setTransform(-66.625,63.3);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#E41C70").s().p("AhDBPIASgfQARAPAVAAQAWgBANgQQANgPAAgWIAAgFQgIALgNAGQgOAIgOAAQgbAAgSgQQgUgPABgeQAAgcATgSQAVgUAgABQApAAAVAdQAUAagBAqQABAsgYAbQgYAcgpAAQghgBgXgTgAgbg0QgJAIAAALQAAAOAMAHQAJAIAOgBQAXAAAOgSQgBgPgJgLQgKgMgSAAQgPAAgKAJg");
	this.shape_51.setTransform(-84.15,63.1);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#E41C70").s().p("AghAQIAAgfIBDAAIAAAfg");
	this.shape_52.setTransform(-97.125,65.75);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#E41C70").s().p("Ag5BGQgUgbABgrQAAgrAWgbQAZgcAoAAQAiABAXATIgTAgQgPgPgXgBQgUABgNAQQgNAPgBAWIAAAFQAHgLANgGQAOgIAPAAQAbAAASAQQAUAQAAAdQgBAcgTASQgVATggAAQgpAAgVgcgAgkAYQACAQAIAKQALAMARAAQAQABAJgKQAJgIAAgLQAAgOgLgHQgJgHgPAAQgWAAgPASg");
	this.shape_53.setTransform(-110,63.15);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#E41C70").s().p("Ag5BGQgUgbAAgrQAAgrAXgbQAZgcAoAAQAiABAXATIgTAgQgQgPgWgBQgUABgOAQQgNAPAAAWIAAAFQAIgLAMgGQAOgIAOAAQAcAAASAQQATAQABAdQAAAcgVASQgUATggAAQgpAAgVgcgAgkAYQACAQAIAKQALAMARAAQAPABAKgKQAJgIAAgLQAAgOgKgHQgKgHgPAAQgWAAgPASg");
	this.shape_54.setTransform(-127.3,63.15);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#E41C70").s().p("Ag0BVQgXgOAAgaQAAgQALgNQAMgNARgFQgmgNAAggQAAgaAYgNQAUgMAdAAQAeAAAUAMQAXANAAAaQAAAgglANQASAFAKANQANANAAAQQAAAagYAOQgVANggAAQgfAAgVgNgAgVAWQgOAIAAAKQAAAKALAGQAKAGAOAAQAPAAAKgGQAKgGAAgKQAAgKgNgIQgKgGgMgBQgLABgKAGgAgWg4QgJAGAAAKQAAAQAfAGQAggFAAgRQAAgKgJgGQgIgFgPgBQgNABgJAFg");
	this.shape_55.setTransform(-144.75,63.15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26}]}).wait(1));

	// phone icon
	this.instance = new lib.phone2rubinecircleai("synched",0);
	this.instance.setTransform(-432.2,67.65,1.5,1.5,0,0,0,27.1,27.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// mask
	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("EgzEAJ3IAAztMBmJAAAIAATtg");
	this.shape_56.setTransform(-176.9,68.925);

	this.timeline.addTween(cjs.Tween.get(this.shape_56).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.EndScreen, new cjs.Rectangle(-503.8,5.8,653.8,126.3), null);


// stage content:
(lib.CO_AEP_300x50 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,538];
	// timeline functions:
	this.frame_0 = function() {
		//if(!this.alreadyyExecuted){
		//this.alreadyyExecuted=true;
		//	this.clickthru_btn.on("click", function(evt){
		//  window.open(clickTag, "_blank");
		//});
		//} else {
		//gotoAndPlay(2);
		//}
	}
	this.frame_538 = function() {
		//if(!this.alreadyExecuted){
		//this.alreadyExecuted=true;
		//this.loopNum=1;
		//} else {
		//this.loopNum++;
		//if(this.loopNum==3){
		this.stop();
		//}
		//}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(538).call(this.frame_538).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(1,2,0,3).p("A3Wj0MAutAAAIAAHpMgutAAAg");
	this.shape.setTransform(150,25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(539));

	// HEAD2
	this.instance = new lib.HEAD2();
	this.instance.setTransform(150,72,1,1,0,0,0,0,24);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(71).to({_off:false},0).to({y:32,alpha:1},13,cjs.Ease.quadOut).wait(97).to({alpha:0},7).to({_off:true},1).wait(350));

	// HEAD4
	this.instance_1 = new lib.HEAD4();
	this.instance_1.setTransform(150,72,1,1,0,0,0,0,24);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(189).to({_off:false},0).to({y:32,alpha:1},13,cjs.Ease.quadOut).wait(118).to({alpha:0},7).to({_off:true},1).wait(211));

	// END SCREEN
	this.instance_2 = new lib.EndScreen();
	this.instance_2.setTransform(251.95,19.1,0.735,0.735,0,0,0,0.1,59.1);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(328).to({_off:false},0).to({alpha:1},13).wait(183).to({alpha:0},13,cjs.Ease.quadOut).to({_off:true},1).wait(1));

	// LOGO
	this.instance_3 = new lib.LOGO();
	this.instance_3.setTransform(157.35,26.85,0.92,0.92,0,0,0,8,21.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({_off:true},71).wait(467).to({_off:false,x:117.95},0).wait(1));

	// CTA
	this.instance_4 = new lib.CTA_mobile();
	this.instance_4.setTransform(254.5,27);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(538).to({_off:false},0).wait(1));

	// BKGD-rubine
	this.instance_5 = new lib.BKGDrubine();
	this.instance_5.setTransform(-63.75,49.2,2.4267,0.36,0,0,0,0.1,67.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(539));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-278,4.9,640.2,88.39999999999999);
// library properties:
lib.properties = {
	id: '0957C5EC3B874C629166840920B09671',
	width: 300,
	height: 50,
	fps: 36,
	color: "#999999",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0957C5EC3B874C629166840920B09671'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;